### ISSUE TITLE
Caught PDOException can not be sent to Bugsnag

### ISSUE THREAD

**Issue by joydasolive** [bugsnag/bugsnag-laravel#102]
I am catching all exceptions and return appropriate responses from the controller. Before returning the response, I log them to the file as well as sending them to Bugsnag. This works for all the exceptions but PDOException. When this exception occurs, the log writes fine but it doesn't get to Bugsnag and my custom response doesn't get returned. instead I get a 500 error. So something must have gone wrong in the notifyException call.

```
Log::error($exception);
Bugsnag::notifyException($exception,$meta_data);
return response()->json(['status'=>false], 500);
```

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Could you please check your php level log file to see what the exception is so we can fix this for you?

**Comment by nviitala** [comment]
I am having the same problem:

QueryException in Connection.php line 770:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'latest_ip' cannot be null (SQL: insert into `xxx` (...) values (...))

I don't handle the QueryException in any way. The page returns HTTP 500.

Every other error gets logged to the BugSnag automatically.

**Comment by brnmonteiro** [comment]
any solution? bugsnag is not loging pdoexceptions
