### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by avasa** [bugsnag/bugsnag-laravel#103]
Hi,

I am getting a 502 on my local environment whenever I switch ExceptionHandler to BugsnagExceptionHandler.

Someone else has also reported the issue, which can be seen below.

http://stackoverflow.com/questions/31428057/guzzlehttp-kills-php-fpm-when-trying-to-post-to-ssl-secured-url

Does anybody have any suggestions?

Thanks in advance.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Please check your PHP logs. I think there is being an exception thrown while trying to contact Bugsnag's servers. This could be due to failed SSL negotiation.
