### ISSUE TITLE
Uncaught ReflectionException: Class bugsnag does not exist ...

### ISSUE THREAD

**Issue by nickurt** [bugsnag/bugsnag-laravel#105]
Hello,

I am using this plugin for a long time, but since today I can't get it working after 

    php composer.phar update

I'm getting;

    PHP Fatal error:  Uncaught ReflectionException: Class bugsnag does not exist in [..]/bootstrap/cache/compiled.php:1291

Any idea how to solve this?, I'm using Laravel 5.1.36 with the latest version of bugsnag-laravel ...

**Comment by GrahamCampbell** [comment]
It looks like your application is crashing before bugsag's service provider was registered.

**Comment by nickurt** [comment]
Thanks, I did a rollback and updated the plugins again, after that all was working fine. It looks like something crashed during the update.
