### ISSUE TITLE
Allow disable notifying

### ISSUE THREAD

**Issue by mverma16** [bugsnag/bugsnag-laravel#106]
Hi,
We've implemented bugsnag in our [project](https://github.com/ladybirdweb/faveo-helpdesk) and we want to provide end user an option to disable bugsnag reporting. 
Can I set an environment variable in config to disable bugsnag reporting while handling errors? Is there any way to do this?

**Comment by kattrali** [comment]
Hi @mverma16. Actually yes, you can disable Bugsnag reporting a few ways. First, you can set [`BUGSNAG_NOTIFY_RELEASE_STAGES`](http://docs.bugsnag.com/platforms/php/laravel/configuration-options/#environment-variables) to exclude the unwanted release stage (for example, if you do not want to report errors from `development`, you could set it to `production`. Alternately, you can disable automatic error reporting using [`setAutoNotify`](http://docs.bugsnag.com/platforms/php/laravel/configuration-options/#setautonotify). Does that answer your question?

**Comment by mverma16** [comment]
I contacted bugsnag support and they suggested to return false in callback function based on user's selected option for reporting.
`Bugsnag::setBeforeNotifyFunction(function ($error) {
                return false;
            });`
Which worked for me. @kattrali, I'll try to setAutoNotify as false now and let you know if it works or not.
