### ISSUE TITLE
Correct placement of setBeforeNotifyFunction

### ISSUE THREAD

**Issue by simplenotezy** [bugsnag/bugsnag-laravel#107]
Where is would be a proper place to put `setBeforeNotifyFunction`? I have tried into Handler.php@report, however meta data is not being sent when I view in Bugsnag.

![image](https://cloud.githubusercontent.com/assets/3786627/15928360/bab509de-2e46-11e6-96a5-fb09f466dd3a.png)

**Comment by GrahamCampbell** [comment]
You can register it in the `boot` function of your app service provider.

**Comment by simplenotezy** [comment]
Thanks!

Also, user[id] cannot be set. It will apparently always default to the IP.

**Comment by simplenotezy** [comment]
My guess is that, this is a bug on Bugsnag's end though.

**Comment by GrahamCampbell** [comment]
Oh, I see. The user isn't meta data. You need to set the user using the setUser function.

**Comment by GrahamCampbell** [comment]
Looking at your code from the screen shot, I don't think that would resolve the correct function actually too.

**Comment by simplenotezy** [comment]
Can you provide an example?

**Comment by GrahamCampbell** [comment]
I'm about to add a setUser function to the error class so that you can use that. Sorry about this!

**Comment by GrahamCampbell** [comment]
I'll get back to you once we've shipped `v1.9.0` of our PHP library.

**Comment by GrahamCampbell** [comment]
To explain what's going on here with the meta data behaving like this... On our side, we throw away the user information from the meta data if separate user data has been set. That's why this is happening (since the php library sets the user id to the IP address).

**Comment by GrahamCampbell** [comment]
You should be able to write this in the boot method of you service provider now:

```php
Bugsnag::setBeforeFunction(function ($error) {
    if (Auth::check()) {
        $error->setUser([/* ... */]);
    }
}
```

The release of v2.9.0 is imminent.

**Comment by GrahamCampbell** [comment]
Ok, the release is out: https://github.com/bugsnag/bugsnag-php/releases/tag/v2.9.0. Please let me know if you run into any problems with it.
