### ISSUE TITLE
lumen's don't report

### ISSUE THREAD

**Issue by RTLer** [bugsnag/bugsnag-laravel#130]
i used bugsnag in lumen project and use installation guide to install it, but i had problem `$dontReport` that just adding `$app('bugsnag')->notifyException($e, null, "error");` into report was ignored it, i pass it by adding an if like so:
```php
if($this->shouldReport($e)){
    app('bugsnag')->notifyException($e, null, "error");
}
```

**Comment by GrahamCampbell** [comment]
Thanks. We're releasing a new major version soon that totally fixes all the lumen issues by overwriding the psr logger rather than overwriting the exception handler.

**Comment by RTLer** [comment]
thx for the response
