### ISSUE TITLE
"composer update" uses Bugsnag v3

### ISSUE THREAD

**Issue by ChristianChoi** [bugsnag/bugsnag-laravel#141]
When performing a "composer update", Bugsnag is upgraded to the new major version 3, which the Service Provider (and more?) doesn't support yet.

**Comment by ChristianChoi** [comment]
Was using 1.6 but issue seems to have been fixed in 1.7

**Comment by GrahamCampbell** [comment]
Yeh, sorry about that. We'd recommend using the version constraint `^1.7` to be sure composer won't try to resolve 1.6 to satisfy some other requirements.
