### ISSUE TITLE
Use Logging contract

### ISSUE THREAD

**Issue by freekmurze** [bugsnag/bugsnag-laravel#146]
Hi,

would you consider to add the logging contract `Illuminate\Contracts\Logging\Log` on `Bugsnag\BugsnagLaravel\ LaravelLogger`?

This would solve issues like [this one at laravel-backup](https://github.com/spatie/laravel-backup/issues/170).

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Yes, of course. I'll look into this for you.

**Comment by GrahamCampbell** [comment]
Please check out my PR and let us know what you think.

**Comment by freekmurze** [comment]
Seems like a good solution to me! 👍

**Comment by GrahamCampbell** [comment]
Please let me know if it works for you. If so, I'll look into getting a release out soon with this change in.

**Comment by aaronhuisinga** [comment]
Using the latest Laravel Backup release and this PR, I was successfully able to run a backup and use the notifier. Seems like this does the trick!

**Comment by GrahamCampbell** [comment]
We will release this on monday is there are no issues discovered, :)

**Comment by freekmurze** [comment]
Thank you very much!
