### ISSUE TITLE
Automatically set the app type

### ISSUE THREAD

**Issue by GrahamCampbell** [bugsnag/bugsnag-laravel#162]
Something like:

```php
$client->setAppType($app->runningInConsole() ? 'Console' : 'Web');
```

needs adding.

**Comment by kattrali** [comment]
Why?

**Comment by GrahamCampbell** [comment]
Otherwise the app type is always unset. I think web and consolake good defaults, right?

**Comment by GrahamCampbell** [comment]
Unset unless the user sets them of course, but they still can set something different on top if they want.

**Comment by kattrali** [comment]
Sure, though I was wondering if it helps you debug in some way to know if it's console vs. web.

**Comment by GrahamCampbell** [comment]
Yeh, definitely, in the same way it's useful to know if it was Sidekiq or not on ruby.
