### ISSUE TITLE
Notifications from Tinker

### ISSUE THREAD

**Issue by b12k** [bugsnag/bugsnag-laravel#175]
Greetings!
I have a problem.
I've set Bugsnag up according to official instructions https://docs.bugsnag.com/platforms/php/laravel/ and those on dashboard ("integrate now").
When I try to do a test error notification using ```php artisan tinker``` nothing happens, no errors, no Bugsnag requests (I use Fiddler), nothing at all. Dashboard stays empty =(

http://prntscr.com/c2ntlz

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Have you setup the API key correctly? Please run `config('bugsnag')` to check the config is set. It it does not appear, perhaps you forgot to run `php artisan config:cache`?

**Comment by koenvu** [comment]
Not sure if this is related, but check your PHP error log and see if there is anything related to a cURL error 60 related to SSL certificates.

If so, you might need to download the cert bundle from somewhere and add that to your PHP config. See this link as well: https://laracasts.com/discuss/channels/general-discussion/curl-error-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate/replies/37017

**Comment by GrahamCampbell** [comment]
You shouldn't need to download a curl bundle. We already have a fix in place for that.

**Comment by koenvu** [comment]
Since when? This solved my issue literally last night.

<img width="1310" alt="php_error_log" src="https://cloud.githubusercontent.com/assets/1215751/17462649/f3e88c30-5cb3-11e6-8e72-c750152d2f23.png">

**Comment by GrahamCampbell** [comment]
Since our very latest release. :)

**Comment by koenvu** [comment]
Sweet 👍

**Comment by koenvu** [comment]
Attempt no. 2 at helping you: when notifying from Tinker, you might have to `exit` out after the `Bugsnag::notifyError`, because it might add the message to a queue which is emptied when finishing the request, i.e. when you finish your Tinker session. Closing out using Ctrl+C won't work, you might really have to use the `exit` command. Don't know if you tried that already.

**Comment by GrahamCampbell** [comment]
Oh, right, yes, that is correct. We enable batch sending by default. You can call `Bugsnag::flush()` to force it to send the queued messages to Bugsnag. By default we do this between queue jobs in the daemon queue, or on shutdown.

**Comment by b12k** [comment]
Hmmm...
Sorry fellows but I didn't get what should I do to make it work =(
(Just did ```composer up```)
http://prntscr.com/c2q50m

Just FYI: Win10 + Xampp

**Comment by b12k** [comment]
Ah OK... waiting this to be merged https://github.com/bugsnag/bugsnag-laravel/pull/176
