### ISSUE TITLE
Using Bugsnag Multi in Lumen

### ISSUE THREAD

**Issue by paulredmond** [bugsnag/bugsnag-laravel#180]
I am trying to integrate the `bugsnag.multi` alias so I can continue to get physical logs and also send them to bugsnag. I think I am missing something, any help would be appreciated.

I am not quite sure how to configure it properly, my interpretation of the [documentation](https://docs.bugsnag.com/platforms/php/laravel/#reporting-unhandled-exceptions) was:

```php
// In AppServiceProvider.php

public function register()
{
    $this->app->alias('bugsnag.multi', \Illuminate\Contracts\Logging\Log::class);
    $this->app->alias('bugsnag.multi', \Psr\Log\LoggerInterface::class);
}
```

The `$app['log']` dependency fails on this line in the `BugsnagServiceProvider` with the above configuration.

```php
$this->app->singleton('bugsnag.multi', function (Container $app) {
    return new MultiLogger([$app['log'], $app['bugsnag.logger']]);
});
```

**Comment by GrahamCampbell** [comment]
Please can you show me your whole file where you register these service providers.

**Comment by GrahamCampbell** [comment]
I've replicated this issue on our example app.

Please could you change the register code to the following:

```php
public function register()
{
    $this->app->extend(\Psr\Log\LoggerInterface::class, function ($logger, $app) {
        return new \Bugsnag\BugsnagLaravel\MultiLogger([$logger, $app['bugsnag.logger']]);
    });
}
```

**Comment by paulredmond** [comment]
@GrahamCampbell thanks for investigating my issue, this clears it up. I've been using Laravel for a while, but I wasn't familiar with `extend`, thanks 👍

**Comment by GrahamCampbell** [comment]
I don't think it's actually documented anywhere in the laravel docs.
