### ISSUE TITLE
FatalErrorException not shown in bugsnag

### ISSUE THREAD

**Issue by dimsav** [bugsnag/bugsnag-laravel#19]
Hi,

the following exception is not caught by bugsnag-laravel:

```
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 
'Allowed memory size of 1585446912 bytes exhausted (tried to allocate 3136499043 bytes)' 
in /home/site.com/app/app/controllers/FileController.php:55
```

Any ideas why?

I know there is an issue in my code but still, bugsnag should be showing this error.

**Comment by onbjerg** [comment]
As of Laravel 5 this can be fixed by adding ``Bugsnag::notifyException(new Exception("Something bad happened"));`` to the custom exception handler bundled with Laravel in app/Exceptions/Handler.php

**Comment by dimsav** [comment]
@onbjerg :+1:

@ConradIrwin this should definitely be on the readme file.

**Comment by ConradIrwin** [comment]
This is fixed in Laravel 5, which we now support!

**Comment by brayann** [comment]
What about Laravel 4? no support anymore? :(

**Comment by onbjerg** [comment]
@brayann Use an older version of the package.

**Comment by duncanhewett** [comment]
@brayann See the legacy integration docs here: https://docs.bugsnag.com/platforms/php/laravel/legacy/

**Comment by brayann** [comment]
@duncanhewett I was asking about the fix for the memory limit error

**Comment by GrahamCampbell** [comment]
It is not possible in PHP to catch an out of memory exception:

![image](https://cloud.githubusercontent.com/assets/2829600/24838116/81f76d98-1d39-11e7-8e7b-9ca82fc00722.png)
