### ISSUE TITLE
2.3.0 - configuration file should not be required

### ISSUE THREAD

**Issue by gabrielpeixoto** [bugsnag/bugsnag-laravel#195]
I updated my Laravel to 5.3 and bugsnag-laravel to 2.3.0.

I had not published the configuration file before using `vendor:publish`, because at https://docs.bugsnag.com/platforms/php/laravel/ it states that: 
"If you’d like to configure Bugsnag further, create and edit a configuration file"

However during the update I got an error because in `$config = $app->config->get('bugsnag');` $config was NULL.

If I publish the config file this problem disapears.

**Comment by GrahamCampbell** [comment]
No need to publish. Just make sure you run the config:cache command after making changes.

**Comment by gabrielpeixoto** [comment]
Perfect!
