### ISSUE TITLE
setUser in AppServiceProvider boot not working

### ISSUE THREAD

**Issue by swilla** [bugsnag/bugsnag-laravel#201]
I'm having trouble setting the user meta data, I'm not using the built-in Laravel Auth, so I added the following to the boot method in the AppServiceProvider:

```
if (app('Dingo\Api\Auth\Auth')->user()) {
            $user = app('Dingo\Api\Auth\Auth')->user();
            $userData = [
                'id' => $user->id,
                'name' => $user->first_name.' '.$user->last_name,
                'email' => $user->email,
                'username' => $user->username,
            ];

            Bugsnag::registerCallback(function ($report) use ($userData) {
                $report->setUser($userData);
            });
        } elseif (Sentry::check()) {
            $user = Sentry::getUser();
            $userData = [
                'id' => $user->id,
                'name' => $user->first_name.' '.$user->last_name,
                'email' => $user->email,
                'username' => $user->username,
            ];
            Bugsnag::registerCallback(function ($report) use ($userData) {
                $report->setUser($userData);
            });
        }
```

It seems like it's not detecting the logged in user.  It's almost like the boot method is being called before the user session is there.

**Comment by GrahamCampbell** [comment]
I think that's probably true, however that's not a bug in our code, rather, a bug in your code there.

One moment please while I provide you with some code that should work...

**Comment by GrahamCampbell** [comment]
```php
$resolver = function ($report) {
    if ($user = app('Dingo\Api\Auth\Auth')->user() ?: Sentry::getUser()) {
        return [
            'id' => $user->id,
            'name' => $user->first_name.' '.$user->last_name,
            'email' => $user->email,
            'username' => $user->username,
        ];
    }
};

$client->registerCallback(new \Bugsnag\Callbacks\CustomUser($resolver));
```

**Comment by swilla** [comment]
Thanks for the suggestion, this didn't work for me either.  As a work around, I placed this call back in the OAuthServiceProvider right after the user is retrieved.  Thanks for the suggestion. Hopefully I can get rid of Sentry soon enough.

**Comment by GrahamCampbell** [comment]
And you definitely put all this user resolving code inside the callback, and not outside? If you do that, it should make no difference where you put the code.
