### ISSUE TITLE
How to use this package on Laravel 5.3

### ISSUE THREAD

**Issue by slakbal** [bugsnag/bugsnag-laravel#203]
Hi,

Tried to install according to the documentation on L5.3 project without any success sofar?

https://docs.bugsnag.com/platforms/php/laravel/

Look from the bugsnag site if this is the package it uses, right? 

I'm going to upgrade the project to L5.3, hence the question. The Projet is currently on 5.2.*.

I think it here:

$this->app->alias('bugsnag.logger', \Illuminate\Contracts\Logging\Log::class);
$this->app->alias('bugsnag.logger', \Psr\Log\LoggerInterface::class);

When I as above artisan command/app is dead... 

Bugsnag bootstrapping
//$this->app->alias('bugsnag.logger', \Illuminate\Contracts\Logging\Log::class);
$this->app->alias('bugsnag.logger', \Psr\Log\LoggerInterface::class);

Also maybe I missed it, but if logging is set to "daily" bugsnag also stops working.

Whe I comment out the above row, it seems to work. And how do I active queueing?

How to proceed please?

Thanks!

**Comment by GrahamCampbell** [comment]
Installing on 5.3 is identical to installing on 5.2.
