### ISSUE TITLE
Include monolog hander for Log:: facade

### ISSUE THREAD

**Issue by pdbreen** [bugsnag/bugsnag-laravel#204]
Hey @GrahamCampbell  - I forked this repo (https://github.com/meadsteve/MonoSnag) to create a v3.4 compatible monolog wrapper (https://github.com/pdbreen/MonoSnag). Then, in AppServiceProvider::boot(), I added the following:

```
$monolog = \Log::getMonolog();
$bugsnagHandler = new BugsnagHandler(app()['bugsnag'], config('jr.error_level'));
$monolog->pushHandler($bugsnagHandler);
```

Seems like you might be able to roll this or something similar into your package with an appropriate config setting to set the logger level (or disable).

**Comment by GrahamCampbell** [comment]
We already support integration with the psr logger, which is the standard. Can I ask why you need monolog please. I'm just trying to understand the use case. :)

**Comment by pdbreen** [comment]
I've got an existing project that already makes use of the Laravel Log facade.  Without the monolog adapter, I couldn't find any way for Bugsnag to report on those errors.  Even tried adding a test log route to the laravel sample in the repo with no luck - only the exception test route would report to Bugsnag.

**Comment by GrahamCampbell** [comment]
Ah, right, yeh. That is a limitation of Laravel where we can't rebind the facade.

**Comment by GrahamCampbell** [comment]
If you resolve the logger interface from the ioc, that'll work though.

**Comment by GrahamCampbell** [comment]
Like find and replace `Log::` with `app('Psr\Log\LoggerInterface')->`.

**Comment by GrahamCampbell** [comment]
I guess the real way we can fix this in laravel's core is to change the facade binding to that interface, then it'll just work.

**Comment by pdbreen** [comment]
Thanks - I should be able to switch from facade to ioc in this project (and will avoid the facade in future projects).  You can feel free to close this (or leave as possible future enhancement).  In either case, would be great to add a comment to the docs that the Log:: facade is not supported.

Thanks again

**Comment by GrahamCampbell** [comment]
This could be fixed in L5.4 if I change the facade to use the psr interface.

**Comment by GrahamCampbell** [comment]
https://github.com/laravel/framework/pull/15855
