### ISSUE TITLE
Registering in AppServiceProvider

### ISSUE THREAD

**Issue by rossjcooper** [bugsnag/bugsnag-laravel#206]
I am having an issue when adding  the following to my AppServiceProvider:

```php
# ADD this to the register method
$this->app->alias('bugsnag.logger', \Illuminate\Contracts\Logging\Log::class);
$this->app->alias('bugsnag.logger', \Psr\Log\LoggerInterface::class);
```

The app simply errors with 500 and cannot get it to output and error log anywhere.

Only thing I found was 
`local.ERROR: exception 'ReflectionException' with message 'Class bugsnag.logger does not exist'`

**Comment by GrahamCampbell** [comment]
Please make sure you put our service provider above the app provider.

**Comment by rossjcooper** [comment]
Thanks again @GrahamCampbell I did try that and it turns out another package also needed to go above my app provider which never caused an error until I included this one.

**Comment by sakinobashi** [comment]
I was having this issue as well, even though I had your service provider above the app provider. The issue, in my case, was that I had the following code on AppServiceProvider's boot() method:
`\Log::getMonolog()->popHandler();`
`\Log::useDailyFiles(storage_path('/logs/laravel-').php_sapi_name().'-'.get_current_user().'.log');`

This was meant to overcome a permission issue I couldn't quite fix – I'm hardly an experienced developer, and this workaround was as good as actually fixing the permissions on practice.

I wanted to keep the default logs as well as bugsnag, but if I can't manually set the filenames the permissions issue will come back. Is there any way to both use bugsnag.multi and rename the default log files as before?
