### ISSUE TITLE
Setting user values in the report

### ISSUE THREAD

**Issue by nfauchelle** [bugsnag/bugsnag-laravel#208]
Hello,

I am having a hard time trying to populate some extra information into the BugSnag report. I have a Laravel 5.2 app running the latest bugsnag-laravel.

From the docs it says by default if the user is logged in, then the id will be included. I have tested this and I always just get the IP.

I am trying to set the id and also a company id. In my ```AppServiceProvider``` in the boot method I added
```
        \Bugsnag::registerCallback(function ($report) {
            $report->setMetaData([
                'user' => [
                    'company_id' => \Session::get('company_id'),
                ]
            ]);
        });
```
and I am getting a null value.

If I do
```
        \Bugsnag::registerCallback(function ($report) {
            dd(\Session::all());
        });
```
then I get back ```[]```

I've also tried ```app\Exceptions\Handler.php``` in the report method. Same deal. It's almost like it's sending bugs before the middleware is firing / session starts.

To trigger a bug I am renaming a controller.

**Comment by GrahamCampbell** [comment]
> and I am getting a null value.

Right, that's due to the fact that the session is not loaded yet in Laravel surely? Unrelated to Bugsnag?

**Comment by GrahamCampbell** [comment]
If you move the session middleware off the routing layer over to the global layer, it'll get executed before routing happens so you should get the information on the reports.

**Comment by nfauchelle** [comment]
@GrahamCampbell 
Thanks for the reply.

We also run an API on some rotues, so global probably wouldn't be ideal.
What if in the _registerCallback_ function we started the session if it wasn't started already... ?

**Comment by GrahamCampbell** [comment]
Then we'd try to start it on your API requests and cause Laravel to send back a session though.

**Comment by GrahamCampbell** [comment]
I don't think it's Bugsnag's place to interfere with your app quite that much.

**Comment by GrahamCampbell** [comment]
You could always forcefully start it yourself if you wanted, within your callback.

**Comment by nfauchelle** [comment]
Thanks Graham.
Turns out I don't need to make any changes with most of the issues since they happen after the session is started so I get the data. I was just testing on bugs very high up.

Thanks for the replies.
