### ISSUE TITLE
Lumen Bugsnag without Facade

### ISSUE THREAD

**Issue by jeffersonsetiawan** [bugsnag/bugsnag-laravel#209]
Hi,

Just curious if we can use Bugsnag in lumen without Facade.

I got this error when using Lumen without Facade. 
`Call to undefined method Bugsnag\BugsnagLaravel\LaravelLogger::setHandlers()`

**Comment by GrahamCampbell** [comment]
Interesting. Looks like a bug in laravel trying to call a method not defined in it's interface.

The fastest way to mitigate this would probably be for Bugsnag to just go ahead and implement this method.

**Comment by GrahamCampbell** [comment]
No such method `setHandlers` exists anywhere in laravel or lumen. Perhaps you are calling it incorrectly, yourself?

**Comment by GrahamCampbell** [comment]
Closing this for now. If you have any more questions, feel free to still reply. :)
