### ISSUE TITLE
Add Console Information

### ISSUE THREAD

**Issue by dbpolito** [bugsnag/bugsnag-laravel#211]
When we have a error on a HTTP Request, a lot of useful info is there on Request and Session tab...

For Console, would be awesome if we have the arguments and options on that command... like:

````
php artisan name:command arg1 arg2 --option=2
````

**Comment by GrahamCampbell** [comment]
Nice idea. I like it.

Currently, all Bugsnag does on Laravel is to set the type to "HTTP", "Console", or "Queue".

I agree that having a tab with more information about the console command would be a nice feature.
