### ISSUE TITLE
Any way to filter sensitive data from URL?

### ISSUE THREAD

**Issue by halaei** [bugsnag/bugsnag-laravel#212]
I have sensitive data in webhook URLs, like `https://www.example.com/webhook/5/<token>`, that are shown in bugsnag panel. Is there any way to filter them into `https://www.example.com/webhook/5/[filtered]`.

**Comment by GrahamCampbell** [comment]
Yes, you can add your own filters by using callback functionality to modify the report object. There's some docs at https://docs.bugsnag.com/platforms/php/laravel/customizing-error-reports/#adding-callbacks, and the source code for the report object is available at https://github.com/bugsnag/bugsnag-php/blob/v3.4.0/src/Report.php.

You can modify the "context" by calling the `getContext` method on the report from within your callback function, and then call the `setContext` method on the report to set it again after you modify it. For completeness, it may be helpful for you to see how the context gets set in the first place: https://github.com/bugsnag/bugsnag-php/blob/v3.4.0/src/Callbacks/RequestContext.php. Hopefully the internals make more sense now. :)

Note that you may also want to filter the URL out of the metadata too. You can do this in a similar way. The metadata is set by another internal callback (https://github.com/bugsnag/bugsnag-php/blob/v3.4.0/src/Callbacks/RequestMetaData.php), which gets the url from https://github.com/bugsnag/bugsnag-laravel/blob/v2.4.0/src/Request/LaravelRequest.php#L70, so you can get the url from the metadata by calling `getMetaData` on the report object, then mutate the value at the `url` key, then set it back with `setMetaData`.

**Comment by GrahamCampbell** [comment]
Here's a complete example (using PHP 7.x sytnax):

```php
<?php

use Bugsnag\Report;
use Bugsnag\BugsnagLaravel\Facades\Bugsnag;

Bugsnag::registerCallback(function (Report $report) {
    if ($url = $report->getMetaData()['request']['url'] ?? null) {
        $safe = mutate_url($url);
        $report->setMetaData(['request' => ['url' => $safe]]);
        if ($verb = explode(' ', $report->getContext(), 2)[0] ?? null) {
            $report->setContext("{$verb} {$safe}");
        }
    }
});

function mutate_url($url)
{
    // do something to remove secret content
    return $url;
}
```

---

Disclaimer, I've not actually tested this code, but it should do the job I think. Please let me know if it doesn't or if you have any questions at all. :)

**Comment by halaei** [comment]
Thanks @GrahamCampbell  it seems to be working, except that setMetaData() should be called in non-merge mode:
```php
\Bugsnag::registerCallback(function (Report $report) {
    $meta = $report->getMetaData();
    if ($url = $meta['request']['url'] ?? null) {
        $meta['request']['url'] = mutate_url($url);
        $report->setMetaData($meta, false);
    }
    if ($ctx = $report->getContext()) {
        $report->setContext(mutate_url($ctx));
    }
});
```

**Comment by GrahamCampbell** [comment]
Great. Note that your code there is subtly incorrect through, because the context isn't ever a complete URL, and, indeed, it'll only ever be "verb + url" in the case that the request metadata is set, otherwise, it may be something totally different. That's why I nested the if statements. :)
