### ISSUE TITLE
Migrations wont work when bugsnag is installed

### ISSUE THREAD

**Issue by unitedworx** [bugsnag/bugsnag-laravel#214]
if I comment out bugsnag from my setup commands like "php artisan migrate:status" work fine, however with bugsnag setup the above command does not work and does not output anything as all, expected is my list of migration files and their status.

I have followed the instructions to setup bugsnag

I am on laravel 5.1 LTS

**Comment by GrahamCampbell** [comment]
Thanks for the report, and sorry for the long wait. Without any more information, I'm not sure what I can suggest.

> command does not work and does not output anything as all

Could you show us exactly what happens here. What is your PHP version, and bugsnag-laravel version please?
