### ISSUE TITLE
Bugsnag should fail silently if no API key is provided

### ISSUE THREAD

**Issue by nickma42** [bugsnag/bugsnag-laravel#215]
If we don't provide a bugsnag API key but still include the service provider we get this:

`PHP Fatal error:  Uncaught exception 'Exception' with message 'Bugsnag Error: Invalid API key' in /home/ubuntu/grabble-api/vendor/bugsnag/bugsnag/src/Bugsnag/Client.php:39`

It's the only library we have that has this behavior - Facebook/Stripe SDKs just fail silently. We have a number of environments where we don't necessarily want our code reporting to Bugsnag - seems pointless having to ensure an API key is set wherever we're testing our code.

Thanks!

**Comment by GrahamCampbell** [comment]
What version are you using please?

**Comment by GrahamCampbell** [comment]
If you make sure the API key is at least the empty string, you should be fine, on any recent version.

**Comment by nickma42** [comment]
Ah cool you're right - thanks @GrahamCampbell - was on v1.7.0 too.
