### ISSUE TITLE
Losing capability to add bugsnag an Log to file at the same time on laravel 5.4

### ISSUE THREAD

**Issue by jeffersonsetiawan** [bugsnag/bugsnag-laravel#217]
In previous version of laravel (<5.4), I can use bugsnag and still can Log into log file (storage/logs) at the same time, but after laravel 5.4 release, if I use bugsnag (
```
$this->app->alias('bugsnag.logger', \Illuminate\Contracts\Logging\Log::class);
		$this->app->alias('bugsnag.logger', \Psr\Log\LoggerInterface::class);
```
)
I can't write to log file using Log::info.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, You'll need the `bugsnag.multi` bound, instead of `bugsnag.logger`, and that should fix your issue.

**Comment by GrahamCampbell** [comment]
This is documented at https://docs.bugsnag.com/platforms/php/laravel/#reporting-unhandled-exceptions, but I can see how it's easily missed, since it's not very clear at all. Perhaps we should make the multilogger example into a fill code example.

**Comment by jeffersonsetiawan** [comment]
omg, I read that ```bugsnag.multi``` thing but not tried that yet.

Thanks @GrahamCampbell !!

**Comment by GrahamCampbell** [comment]
Great. :)

**Comment by ankurk91** [comment]
Hi,
I want Laraval (5.4) to store errors in ```storage/logs/laravel.log``` as well as report them to bugsnag.

Take this example -
```php
try {
   throw new Exception('Some error');
} catch (\Exception $e) {

    Bugsnag::notifyException($e);
    // Does this make any difference ?
    Log::error($);
}
```

Above code will report two errors to bugsnag. 
* ```Log::error($e)``` will report error to bugsnag + write to ```laravel.log```
* ```Bugsnag::notifyException($e)``` does not write logs to ```laravel.log```

What is the best way ? Please help.

Here is how i configured bugsnag in ```AppServiceProvide.php``` register() method -
```php
$this->app->alias('bugsnag.multi', \Illuminate\Contracts\Logging\Log::class);
$this->app->alias('bugsnag.multi', \Psr\Log\LoggerInterface::class);
```
