### ISSUE TITLE
Method 'registerUserResolver' doesn't exist

### ISSUE THREAD

**Issue by Pierlo1** [bugsnag/bugsnag-laravel#219]
In the config file, under the _User_ section it is stated:

> ... you can call the Bugsnag::registerUserResolver method from the boot method of your app service provider.

However, no such method exists. I can make a pull request with the changes to fix this if needed.

**Comment by GrahamCampbell** [comment]
Please can you let us know the full class name of "Bugsnag" please?

**Comment by GrahamCampbell** [comment]
It should be the facade, rather than the client.

**Comment by GrahamCampbell** [comment]
Hmmm, this does look like a mistake in the docs actually.

**Comment by GrahamCampbell** [comment]
Actually, I can't find anything in the docs that says that? https://docs.bugsnag.com/platforms/php/laravel/#identifying-users

**Comment by Pierlo1** [comment]
Oh OK I see. i got confused for a second there. It's in the config file: https://github.com/bugsnag/bugsnag-laravel/blob/master/config/bugsnag.php#L212

**Comment by GrahamCampbell** [comment]
Ah, I see now. Thanks for reporting. :)

**Comment by Pierlo1** [comment]
Should I make a pull request or will you do the honors?

**Comment by GrahamCampbell** [comment]
I'm working on one now, but feel free to send one also if you want. It might be better than mine. :)
