### ISSUE TITLE
Bugsnag Direct Log:error calls

### ISSUE THREAD

**Issue by dbpolito** [bugsnag/bugsnag-laravel#221]
Currently if we call `Log::error` it doesn't go to Bugsnag, would be great if we have an option to send all Log calls by default to Bugsnag too.

Could  be easily done with event `illuminate.log` on logs with `error` flag...

But i think if i do that unhandled exceptions would send it twice, i guess...

**Comment by GrahamCampbell** [comment]
Unfortunately, it's not possible to rebind the Log facade without making a mess in Laravel, so you'll need to resolve the contract using the `app()` helper in order to log, then things should go to Bugsnag.

**Comment by dbpolito** [comment]
i don't think you need to rebind log facade... all log calls this event: https://github.com/laravel/framework/blob/5.4/src/Illuminate/Log/Writer.php#L201

So if you add something like should work:

````
Log::listen(function() {
    Bugsnag::notify()
})
````

The only trick part is that unhandled exception also add a record to log, so you would add twice to bugsnag... i think...

**Comment by GrahamCampbell** [comment]
> So if you add something like should work:

The trouble with this, is Laravel's logger already notifies Bugsnag, it's only the facade that can't be rebound. If you do `app('Psr\Log\LoggerInterface')->error(...)` it will work fine.

**Comment by GrahamCampbell** [comment]
Alternatively, upgrading to Laravel 5.4+ will actually fix this bug.

**Comment by GrahamCampbell** [comment]
Alternatively, upgrading to Laravel 5.4+ will actually fix this bug, since I've fixed this in the framework: https://github.com/laravel/framework/pull/15855.

**Comment by dbpolito** [comment]
Cool, another reason to upgrade my app then 👍 which i was already planning to do soon. Thx

**Comment by gyurobenjamin** [comment]
You can create your custom Log facade in your app dir which use the 'Psr\Log\LoggerInterface', change the illuminate one to your new custom one in the aliases and bumm.

**Comment by gyurobenjamin** [comment]
Your new custom facade:
```php
<?php
namespace App\Facades;
/**
 * @see \Illuminate\Log\Writer
 */
class Log extends \Illuminate\Support\Facades\Facade
{
    /**
     * Get the registered name of the component.
     *
     * @return string
     */
    protected static function getFacadeAccessor()
    {
        return 'Psr\Log\LoggerInterface';
    }
}
```
register it in config/app.php
```php
'aliases' => [
    'Log' => App\Facades\Log::class
];
```
