### ISSUE TITLE
Realpath requiring configuration

### ISSUE THREAD

**Issue by praalhans** [bugsnag/bugsnag-laravel#222]
In the Laravel bugsnag ServiceProvider in `setupConfig`, the code mentions that the configuration is located at:

```
    protected function setupConfig(Container $app)
    {
        $source = realpath(__DIR__.'/../config/bugsnag.php');
```

Bundling bugsnag in a web phar archive for easier deployment is broken due to the use of `realpath` here. The PHP interpreter changes the `__DIR__` macro as `phar://path/to/my.phar/.../vendor/bugsnag/.../BugsnagServiceProvider.php` when the file is loaded from such an archive.

Note that removing the `realpath` call should not affect any existing users, since `mergeConfigFrom` simply performs `require $source` on the first parameter, and require will itself resolve the relative path to an absolute path when loading the file.

**Comment by GrahamCampbell** [comment]
Interesting that this doesn't work, but realpath is used else where in laravel?

**Comment by GrahamCampbell** [comment]
> Bundling bugsnag in a web phar archive for easier deployment is broken due to the use of realpath here. 

Could you clarify what you mean here? Do you mean the realpath function says no such path exists?

**Comment by GrahamCampbell** [comment]
If you replace that line with:

```php
$source = realpath($raw = __DIR__.'/../config/bugsnag.php') ?: $raw;
```

does it work properly?

**Comment by praalhans** [comment]
That is correct. However, we only package up all dependencies in the `vendor` directory as a phar archive, not the complete Laravel application. Hence, loading configuration files should work for applications that retrieve the real path of the Laravel root.

I will update this issue when I have tested the patch that removes the `realpath` call, whether this is a problem of Bugsnag or Laravel.

**Comment by GrahamCampbell** [comment]
If you replace that line with:

```php
$source = realpath($raw = __DIR__.'/../config/bugsnag.php') ?: $raw;
```

does it work properly?

**Comment by praalhans** [comment]
Realpath itself will not be modified, which makes sense.

https://bugs.php.net/bug.php?id=52769

Perhaps this bug is larger, in the sense that every application built on Laravel assumes all files to be present on the filesystem.

For us this is a huge problem, since we want to deploy Laravel applications by FTP to sites where we do not have SSH access. The FTP protocol is very slow when sending many smaller files; due to the design of the FTP protocol, each file upload incurs at least one round-trip time.

Our intended solution (for a small Lumen application) is to bundle all vendor dependencies as a web phar file, and include it during bootstrapping.

**Comment by GrahamCampbell** [comment]
Right, but does that modification there work for you please?

**Comment by praalhans** [comment]
Still testing out, we have a long build process (packaging the phar takes some time).

**Comment by praalhans** [comment]
Confirmed. The proposed change resolves the problem in bugsnag.

**Comment by GrahamCampbell** [comment]
Thank you. I'll PR the change then.
