### ISSUE TITLE
A package won't work properly while Bugsnag installed

### ISSUE THREAD

**Issue by meness** [bugsnag/bugsnag-laravel#227]
Hi,

> Argument 3 passed to Spatie\Permission\PermissionRegistrar::__construct() must implement interface Illu  
  minate\Contracts\Logging\Log, instance of Bugsnag\PsrLogger\MultiLogger given

This exception is thrown because I installed Bugsnag package and I bound the Bugsnag PSR logger in the `register()` method of my application service provider `app/Providers/AppServiceProvider.php`

```php
$this->app->alias('bugsnag.multi', \Illuminate\Contracts\Logging\Log::class);
$this->app->alias('bugsnag.multi', \Psr\Log\LoggerInterface::class);
```

**Note:** If I comment above lines, everything would work fine, but they're needed while using Bugsnag

**Note:** A solution from a member of the package is [already provided](https://github.com/spatie/laravel-permission/issues/268#issuecomment-293819350), what's your solution?

**Comment by GrahamCampbell** [comment]
Thanks for the report. I see what's happening here. I'll look into a fix ASAP for you.

**Comment by GrahamCampbell** [comment]
> Bugsnag\PsrLogger\MultiLogger

You will need to use the `Bugsnag\BugsnagLaravel\MultiLogger` class rather than `Bugsnag\PsrLogger\MultiLogger`.

What version of this package are you using please?

**Comment by meness** [comment]
@GrahamCampbell I'm using the latest stable version, and I'm using the following lines and get the exception. I'm still have problem with Bugsnag

```php
$this->app->alias('bugsnag.multi', \Illuminate\Contracts\Logging\Log::class);
$this->app->alias('bugsnag.multi', \Psr\Log\LoggerInterface::class);
```

> [Symfony\Component\Debug\Exception\FatalThrowableError]                                                              
>   Type error: Argument 3 passed to Spatie\Permission\PermissionRegistrar::__construct() must implement interface Illu  
>   minate\Contracts\Logging\Log, instance of Bugsnag\PsrLogger\MultiLogger given

**Comment by meness** [comment]
@GrahamCampbell I test the following lines and everything works well and no exception thrown. Is this okay?

```php
$this->app->alias('bugsnag.multi', \Bugsnag\PsrLogger\MultiLogger::class);
$this->app->alias('bugsnag.multi', \Psr\Log\LoggerInterface::class);
```

**Comment by GrahamCampbell** [comment]
Interesting. What version are you using please? Can you please give me the full output from `composer show` (if this command takes ages or shows packages you don't have, update to the latest version of composer `composer self-update`)?

**Comment by meness** [comment]
@GrahamCampbell 

**Composer version:** 1.4.2 (stable channel)

**`composer show` Output:**

> algolia/algoliasearch-client-php       1.18.0  Algolia Search API Client for PHP
> barryvdh/laravel-debugbar              v2.4.1  PHP Debugbar integration for Laravel
> barryvdh/laravel-ide-helper            v2.4.0  Laravel IDE Helper, generates correct PHPDocs for all Facade clas...
> barryvdh/reflection-docblock           v2.0.4 
> bugsnag/bugsnag                        v3.5.1  Official Bugsnag notifier for PHP applications.
> bugsnag/bugsnag-laravel                v2.0.0  Official Bugsnag notifier for Laravel applications.
> bugsnag/bugsnag-psr-logger             v1.1.0  Official Bugsnag PHP PSR Logger.
> cocur/slugify                          v2.5    Converts a string into a slug.
> composer/ca-bundle                     1.0.7   Lets you find a path to the system CA bundle, and includes a fall...
> cviebrock/eloquent-sluggable           4.2.4   Easy creation of slugs for your Eloquent models in Laravel 5.
> ddelnano/dredd-hooks-php               1.1.5   PHP hooks for the Dredd testing tool
> defuse/php-encryption                  v2.1.0  Secure PHP Encryption Library
> dnoegel/php-xdg-base-dir               0.1     implementation of xdg base directory specification for php
> doctrine/annotations                   v1.4.0  Docblock Annotations Parser
> doctrine/cache                         v1.6.1  Caching library offering an object-oriented API for many cache ba...
> doctrine/collections                   v1.4.0  Collections Abstraction library
> doctrine/common                        v2.7.2  Common Library for Doctrine projects
> doctrine/dbal                          v2.5.12 Database Abstraction Layer
> doctrine/inflector                     v1.1.0  Common String Manipulations with regard to casing and singular/pl...
> doctrine/instantiator                  1.0.5   A small, lightweight utility to instantiate objects in PHP withou...
> doctrine/lexer                         v1.0.1  Base library for a lexer that can be used in Top-Down, Recursive ...
> drewm/mailchimp-api                    v2.4    Super-simple, minimum abstraction MailChimp API v3 wrapper
> erusev/parsedown                       1.6.3   Parser for Markdown.
> firebase/php-jwt                       v4.0.0  A simple library to encode and decode JSON Web Tokens (JWT) in PH...
> flugger/laravel-responder              v1.2.25 A Laravel package for APIs, wrapping the Fractal library behind a...
> fzaninotto/faker                       v1.6.0  Faker is a PHP library that generates fake data for you.
> garygreen/pretty-routes                0.0.6   Pretty routes for Laravel 5.
> guzzlehttp/guzzle                      6.3.0   Guzzle is a PHP HTTP client library
> guzzlehttp/promises                    v1.3.1  Guzzle promises library
> guzzlehttp/psr7                        1.4.2   PSR-7 message implementation that also provides common utility me...
> hamcrest/hamcrest-php                  v1.2.2  This is the PHP port of Hamcrest Matchers
> intervention/image                     2.4.0   Image handling and manipulation library with support for Laravel ...
> jakub-onderka/php-console-color        0.1    
> jakub-onderka/php-console-highlighter  v0.3.2 
> jenssegers/optimus                     v0.2.3  Id obfuscation based on Knuth's integer hash method
> laravel/framework                      v5.4.28 The Laravel Framework.
> laravel/passport                       v2.0.11 Laravel Passport provides OAuth2 server support to Laravel.
> laravel/scout                          v3.0.5  Laravel Scout provides a driver based solution to searching your ...
> laravel/tinker                         v1.0.1  Powerful REPL for the Laravel framework.
> lcobucci/jwt                           3.2.1   A simple library to work with JSON Web Token and JSON Web Signature
> league/event                           2.1.2   Event package
> league/flysystem                       1.0.40  Filesystem abstraction: Many filesystems, one API.
> league/fractal                         0.16.0  Handle the output of complex data structures ready for API output.
> league/glide                           1.2.2   Wonderfully easy on-demand image manipulation library with an HTT...
> league/oauth2-server                   5.1.5   A lightweight and powerful OAuth 2.0 authorization and resource s...
> league/url                             3.3.5   League/url is a lightweight PHP Url manipulating library
> maximebf/debugbar                      1.13.1  Debug bar in the browser for php application
> meness/verifi                          1.0.9   A Laravel package to handle email verification.
> mockery/mockery                        0.9.9   Mockery is a simple yet flexible PHP mock object framework for us...
> monolog/monolog                        1.23.0  Sends your logs to files, sockets, inboxes, databases and various...
> mtdowling/cron-expression              v1.2.0  CRON for PHP: Calculate the next or previous run date and determi...
> myclabs/deep-copy                      1.6.1   Create deep copies (clones) of your objects
> nesbot/carbon                          1.22.1  A simple API extension for DateTime.
> nicolasbeauvais/botscout-client        1.0.1   A PHP client library for botscout.com
> nicolasbeauvais/laravel-botscout       1.0.1   botscout.com protection for laravel
> nikic/php-parser                       v3.0.6  A PHP parser written in PHP
> paragonie/random_compat                v2.0.10 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
> phpdocumentor/reflection-common        1.0     Common reflection classes used by phpdocumentor to reflect the co...
> phpdocumentor/reflection-docblock      3.1.1   With this component, a library can provide support for annotation...
> phpdocumentor/type-resolver            0.2.1  
> phpseclib/phpseclib                    2.0.6   PHP Secure Communications Library - Pure-PHP implementations of R...
> phpspec/prophecy                       v1.7.0  Highly opinionated mocking framework for PHP 5.3+
> phpunit/php-code-coverage              4.0.8   Library that provides collection, processing, and rendering funct...
> phpunit/php-file-iterator              1.4.2   FilterIterator implementation that filters files based on a list ...
> phpunit/php-text-template              1.2.1   Simple template engine.
> phpunit/php-timer                      1.0.9   Utility class for timing
> phpunit/php-token-stream               1.4.11  Wrapper around PHP's tokenizer extension.
> phpunit/phpunit                        5.7.21  The PHP Unit Testing framework.
> phpunit/phpunit-mock-objects           3.4.4   Mock Object library for PHPUnit
> predis/predis                          v1.1.1  Flexible and feature-complete Redis client for PHP and HHVM
> propaganistas/laravel-fakeid           2.0.6   Automatic ID obfuscation for Eloquent models.
> psr/http-message                       1.0.1   Common interface for HTTP messages
> psr/log                                1.0.2   Common interface for logging libraries
> psy/psysh                              v0.8.9  An interactive shell for modern PHP.
> ramsey/uuid                            3.6.1   Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122...
> sebastian/code-unit-reverse-lookup     1.0.1   Looks up which function or method a line of code belongs to
> sebastian/comparator                   1.2.4   Provides the functionality to compare PHP values for equality
> sebastian/diff                         1.4.3   Diff implementation
> sebastian/environment                  2.0.0   Provides functionality to handle HHVM/PHP environments
> sebastian/exporter                     2.0.0   Provides the functionality to export PHP variables for visualization
> sebastian/global-state                 1.1.1   Snapshotting of global state
> sebastian/object-enumerator            2.0.1   Traverses array structures and object graphs to enumerate all ref...
> sebastian/recursion-context            2.0.0   Provides functionality to recursively process PHP variables
> sebastian/resource-operations          1.0.0   Provides a list of PHP built-in functions that operate on resources
> sebastian/version                      2.0.1   Library that helps with managing the version number of Git-hosted...
> softonic/laravel-middleware-request-id v1.0.1  Middleware for Laravel Framework to add the X-Request-ID header i...
> spatie/db-dumper                       2.7.0   Dump databases
> spatie/image                           1.3.2   Manipulate images with an expressive API
> spatie/image-optimizer                 1.0.6   Easily optimize images using PHP
> spatie/laravel-backup                  4.18.0  A Laravel 5 package to backup your application
> spatie/laravel-medialibrary            5.12.0  Associate files with Eloquent models
> spatie/laravel-newsletter              3.6.0   Manage newsletters in Laravel 5
> spatie/laravel-permission              2.2.0   Permission handling for Laravel 5.4 and up
> spatie/laravel-responsecache           3.2.0   Speed up a Laravel application by caching the entire response
> spatie/laravel-url-signer              2.0.0   Laravel implementation of spatie/signed-url
> spatie/pdf-to-image                    1.2.2   Convert a pdf to an image
> spatie/temporary-directory             1.1.2   The `temporary-directory` package allows you to easily create, us...
> spatie/url-signer                      1.0.2   Generate a url with an expiration date and signature to prevent u...
> swiftmailer/swiftmailer                v5.4.8  Swiftmailer, free feature-rich PHP mailer
> symfony/class-loader                   v3.3.4  Symfony ClassLoader Component
> symfony/console                        v3.3.4  Symfony Console Component
> symfony/css-selector                   v3.3.4  Symfony CssSelector Component
> symfony/debug                          v3.3.4  Symfony Debug Component
> symfony/event-dispatcher               v3.3.4  Symfony EventDispatcher Component
> symfony/finder                         v3.3.4  Symfony Finder Component
> symfony/http-foundation                v3.3.4  Symfony HttpFoundation Component
> symfony/http-kernel                    v3.3.4  Symfony HttpKernel Component
> symfony/polyfill-mbstring              v1.4.0  Symfony polyfill for the Mbstring extension
> symfony/process                        v3.3.4  Symfony Process Component
> symfony/psr-http-message-bridge        v1.0.0  PSR HTTP message bridge
> symfony/routing                        v3.3.4  Symfony Routing Component
> symfony/translation                    v3.3.4  Symfony Translation Component
> symfony/var-dumper                     v3.3.4  Symfony mechanism for exploring and dumping PHP variables
> symfony/yaml                           v3.3.4  Symfony Yaml Component
> themsaid/laravel-langman-gui           v0.2.0  Manage language files with ease.
> tightenco/mailthief                    v0.3.6  A fake Mailer for Laravel applications that takes the pain out of...
> tijsverkoyen/css-to-inline-styles      2.2.0   CssToInlineStyles is a class that enables you to convert HTML-pag...
> true/punycode                          v2.1.1  A Bootstring encoding of Unicode for Internationalized Domain Nam...
> vlucas/phpdotenv                       v2.4.0  Loads environment variables from `.env` to `getenv()`, `$_ENV` an...
> webmozart/assert                       1.2.0   Assertions to validate method input/output with nice error messages.
> zendframework/zend-diactoros           1.4.0   PSR HTTP Message implementations

**The exception after running `composer update`:**

> Generating optimized autoload files
> > Illuminate\Foundation\ComposerScripts::postUpdate
> > php artisan clear-compiled
> 
>                                                                                                                        
>   [Symfony\Component\Debug\Exception\FatalThrowableError]                                                              
>   Type error: Argument 3 passed to Spatie\Permission\PermissionRegistrar::__construct() must implement interface Illu  
>   minate\Contracts\Logging\Log, instance of Bugsnag\PsrLogger\MultiLogger given                                        
>                                                                                                                        
> 
> Script php artisan clear-compiled handling the post-update-cmd event returned with error code 1
> 
> Process finished with exit code 1 at 11:26:10.
> Execution time: 81,518 ms.

**Comment by GrahamCampbell** [comment]
> The exception after running composer update:

Oh, so this only happens there? Please try deleting the files in `boostrap/cache`, and running update again.

**Comment by meness** [comment]
@GrahamCampbell Deleting `bootstrap/cache` directory content didn't help.
