### ISSUE TITLE
Exception is sent twice when using bugsnag.multi

### ISSUE THREAD

**Issue by blacklizard** [bugsnag/bugsnag-laravel#230]
Laravel: 5.4.19
bugsnag/bugsnag-laravel: 2.5

Install instruction followed from: https://docs.bugsnag.com/platforms/php/laravel/#installation

![screen shot 2017-05-05 at 2 24 49 pm](https://cloud.githubusercontent.com/assets/1284948/25735555/c60b79ce-319e-11e7-9cd3-78d7302bf152.png)

**Comment by GrahamCampbell** [comment]
Thanks for the report. Where exactly is the syntax error please? It's possible you code is actually causing PHP to require the file with the error twice, so thus meaning there really are two errors there, rather than a double send.
