### ISSUE TITLE
LaravelLogger does not implement Log::listen() and Log::getMonolog(), present in default Log facade

### ISSUE THREAD

**Issue by DfKimera** [bugsnag/bugsnag-laravel#231]
Laravel's Log facade has two very handy functions, `Log::listen()` and `Log::getMonolog()`.

When Bugsnag's handler is added, it replaces the Log facade handler, but it doesn't implement these methods:

![screenshot 2017-05-08 18 31 58](https://cloud.githubusercontent.com/assets/581765/25826353/e14e10ae-341c-11e7-87d8-9fcf32501023.png)

These are very handy for console commands, where log messages coming from internal recyclable classes can be captured and displayed as console output.

Tested with `bugsnag/bugsnag-laravel` at `^2.5` (`2.5.0`)

**Comment by DfKimera** [comment]
Sample usage for `Log::listen()`:

```php
class Command extends \Illuminate\Console\Command {

	protected function setupLogging() {
		Log::listen(function (MessageLogged $msg) {

			if($msg->level == "error") {
				$this->error($msg->message);
				return;
			}

			$this->comment($msg->message);

		});
	}

}

```

**Comment by DfKimera** [comment]
@GrahamCampbell Hey, can I open a PR to fix this, or are you guys already working on it?

**Comment by richstandbrook** [comment]
Also don't seem to be able to test properly when using Bugsnag and `Log::spy()`. 
```
No matching handler found for Mockery_1_Bugsnag_BugsnagLaravel_LaravelLogger::debug()
```

**Comment by GrahamCampbell** [comment]
Thanks everyone. I am working on a fix for this. :)

**Comment by richstandbrook** [comment]
Any progress? I could really do with some Bugsnag reporting!

**Comment by GrahamCampbell** [comment]
@DfKimera, @richstandbrook Please let me know if https://github.com/bugsnag/bugsnag-laravel/pull/239 fixes this for you. :)

**Comment by DfKimera** [comment]
@GrahamCampbell I'm having a Closure type error, seems to be a missing back-slash:

![image](https://user-images.githubusercontent.com/581765/28037649-726965e2-6592-11e7-91be-cc94a3bd9032.png)
By poking the code, I've noticed it is missing a back-slash on `\Closure` in the `EventTrait`:

![image](https://user-images.githubusercontent.com/581765/28037719-c0771e6e-6592-11e7-9705-088d2ab8eaed.png)

By fixing this minor issue, I get another error:

![image](https://user-images.githubusercontent.com/581765/28037743-dec747b8-6592-11e7-9183-040a9f92ca62.png)

For reference, this is the userland code I'm calling:

![image](https://user-images.githubusercontent.com/581765/28037661-7ecb922e-6592-11e7-891a-3cf0ae39048f.png)

**Comment by GrahamCampbell** [comment]
Thanks for trying it out. I'll push some fixes shortly. :)

**Comment by GrahamCampbell** [comment]
Try now. :)

**Comment by DfKimera** [comment]
It's working now! :D

For some reason, the event handler is called three times instead of one. Here's my testing scenario and output:

![image](https://user-images.githubusercontent.com/581765/28039688-9bbc43ea-6599-11e7-90d2-ec4333461988.png)

![image](https://user-images.githubusercontent.com/581765/28039976-8abeaafa-659a-11e7-8be9-f5e17d012d38.png)

![image](https://user-images.githubusercontent.com/581765/28040005-9f309ade-659a-11e7-9d68-15831a0042ac.png)

Here's how I'm registering it in the app service provider:

![image](https://user-images.githubusercontent.com/581765/28040027-b8f333a0-659a-11e7-8f22-73f38d133058.png)

In the log, however, it is registered correctly:

![image](https://user-images.githubusercontent.com/581765/28040091-fb38b4c4-659a-11e7-849c-91038e438224.png)

**Comment by GrahamCampbell** [comment]
Are you calling the log listen method after you've registered the aliases?

**Comment by GrahamCampbell** [comment]
When is setup logging called in your command class? I think that's being called too many times perhapse?

**Comment by DfKimera** [comment]
Yes, the `register` and `alias` calls are in `AppServiceProvider::register`. 

I've tested commenting/uncommenting lines, and this line is what causes the extra calls:

`$this->app->alias('bugsnag.multi', \Psr\Log\LoggerInterface::class);`

Commenting it reduces the calls back to one.

**Comment by DfKimera** [comment]
Here's a snapshot of the entire `AppServiceProvider`, for clarity:

![image](https://user-images.githubusercontent.com/581765/28040372-f73d5f4a-659b-11e7-8805-9d1b4c521aad.png)

**Comment by GrahamCampbell** [comment]
Thanks. Why are you aliasing `Bugsnag` like that. It doesn't look correct. Did you mean to just write `class_alias`? The service container aliases have a very specific use, and it's not a good idea to use them to shorten class names.

Is you app service provider registered after the bugsnag one?

**Comment by DfKimera** [comment]
I'm doing that way because I've opted to only load Bugsnag in the production environment, so it's no longer in `app.php`. Removing that line has no effect. 

I've tried moving back the alias and service provider to the config file, but it still triples the callback call when I add the `\Psr\Log\LoggerInterface` Bugsnag alias.

**Comment by DfKimera** [comment]
Oh, to answer your previous question: `setupLogging()` is called only once, on the command `handle()`.

**Comment by GrahamCampbell** [comment]
Thanks for the details. I'll investigate soon.

**Comment by GrahamCampbell** [comment]
![image](https://user-images.githubusercontent.com/2829600/28240402-47fd6a84-6979-11e7-9ca2-f49b4d28ef9a.png)

This line definitely is incorrect. Please remove it. A container alias is not at all the same as a class_alias, which is what I assume you want there.

**Comment by GrahamCampbell** [comment]
Did you follow the lumen specific instructions? The multi logger needs different setup to Laravel:

![image](https://user-images.githubusercontent.com/2829600/28240425-9d40a59c-6979-11e7-83fb-76182a06270d.png)

**Comment by GrahamCampbell** [comment]
You will also need to pass in the events instance in, as not shown in the docs, since the docs are for the current version, not this PR. Basically, you need to only write the following, and nothing else:

```php
$this->app->register(Bugsnag\BugsnagLaravel\BugsnagServiceProvider::class);

$this->app->extend(\Psr\Log\LoggerInterface::class, function ($logger, $app) {
    return new \Bugsnag\BugsnagLaravel\MultiLogger([$logger, $app['bugsnag.logger']], $app['events']);
});
```

**Comment by GrahamCampbell** [comment]
Do not try to do aliasing with the `bugsnag.multilogger`, that is laravel specific, and will not work in lumen.

**Comment by DfKimera** [comment]
The app is a Laravel app. I followed the Laravel instructions found [here](https://docs.bugsnag.com/platforms/php/laravel/#basic-configuration).

I've since removed the alias line you mentioned, but it has no effect on the log messages tripling. The line that has this effect is:
```php
$this->app->alias('bugsnag.multi', \Psr\Log\LoggerInterface::class);
```
When I comment this line, the events are no longer tripled.
