### ISSUE TITLE
Redis connection overflow when using Bugsnag::registerCallback

### ISSUE THREAD

**Issue by tmyers273** [bugsnag/bugsnag-laravel#234]
This one has me quite baffled. Ran into it on a production system and after a very long debugging session, have reproduced it here: https://github.com/tmyers273/bugsnag-redis-connection-error

Essentially, when using the registerCallback function
```
Bugsnag::registerCallback(function ($report) {
    $report->setMetaData([
        'Data' => [
            'Very Fake',
            'Data Lives',
            'Here!'
        ]
    ]);
});
```

Redis connections do not seem to be dropped / reused as expected. This very quickly causes Redis to hit the max client limit and start returning
`'AUTH' failed: ERR max number of clients reached`

Removing the register callback seems to resolve the issue.

**Comment by GrahamCampbell** [comment]
I'm not sure how this is related to us. I think the issue is just that redis us using threading, and when php wants to throw an exception, it just rejoins the main thread, so the stacktrace will come from some random place being executed on the main thread. In this case, it was the bugsnag code.
