### ISSUE TITLE
Why does the wrapper marks "info" and "debug" messages as breadcrumbs?

### ISSUE THREAD

**Issue by reshadman** [bugsnag/bugsnag-laravel#235]
I am confused why does the wrapper marks all `info` and `debug` logs as breadcrumbs and there is not any section in the panel to view standalone breadcrumbs?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. This is because Bugsnag is an Error Monitor. The idea is to record errors, and any useful information leading up to them.

**Comment by reshadman** [comment]
It is, but laravel's Log handler is not just for error monitoring, by changing the logger instance in the container to bugsnag's implementation you get different behavior on the same interface. confusing.
