### ISSUE TITLE
Ignore Exceptions

### ISSUE THREAD

**Issue by luisdalmolin** [bugsnag/bugsnag-laravel#24]
Is there a way to ignore some exceptions?

Like: Symfony\Component\HttpKernel\Exception\NotFoundHttpException and Illumiante\Database\Eloquent\ModelNotFoundException.

**Comment by mikevrind** [comment]
Do you happen to have any more news about this issue?
I'm experiencing the same problem with the above exceptions. Both are caught, but are still popping up in Bugsnag.

**Comment by loopj** [comment]
Hey @mikevrind, @luisdalmolin. We don't support this in the notifier right now, but you can choose which classes to ignore in your Bugsnag dashboard, under Settings -> Error Handling -> Ignored Errors.

I hope this helps!

**Comment by loopj** [comment]
Actually, there is a way to do this in code too, by using `Bugsnag::setBeforeNotify`:

```php
Bugsnag::setBeforeNotifyFunction("before_bugsnag_notify");

function before_bugsnag_notify($error) {
    if($error->name == "Symfony\Component\HttpKernel\Exception\NotFoundHttpException") {
      return false;
    }
}
```

See [here](https://github.com/bugsnag/bugsnag-php#setbeforenotifyfunction) for more information.
