### ISSUE TITLE
Filter log events being sent by log level

### ISSUE THREAD

**Issue by scottconnerly** [bugsnag/bugsnag-laravel#240]
Enhancement request:

Currently, every Log event is always sent to Bugsnag. It would be great to have a config that allows us to exclude debug, info level log events.

**Comment by GrahamCampbell** [comment]
Debug and info logs are not sent to Bugsnag at the moment. Only notice logs are sent to bugsnag as info, warning as warning, and others as errors. :)

**Comment by GrahamCampbell** [comment]
Info and debug are captured as breadcrumbs, which may never get set. If you want to change this, the easiest way to customize this is to extend one of our psr loggers. :)
