### ISSUE TITLE
The example app sends multiple reports for a single request to the crashing endpoint

### ISSUE THREAD

**Issue by kattrali** [bugsnag/bugsnag-laravel#243]
If you run the example app (and set your API key), when you visit localhost:8000/test, you get two error reports.

**Comment by GrahamCampbell** [comment]
Is this due to the events PR?

**Comment by kattrali** [comment]
No. Tested back to 2.3.0

**Comment by GrahamCampbell** [comment]
The 5.6 example app doesn't send two error reports I think?

**Comment by kattrali** [comment]
Yep! This is fixed.

**Comment by GrahamCampbell** [comment]
Fixed on the 5.2 sample app too?
