### ISSUE TITLE
Support laravel 5.5

### ISSUE THREAD

**Issue by GrahamCampbell** [bugsnag/bugsnag-laravel#246]
Todo:

* [ ] Add support for package auto discovery
* [ ] Upgrade the example application
* [ ] Test on a real world laravel application

**Comment by KillermenBE** [comment]
@GrahamCampbell 

I'm testing it with a live world application on our Development Server.
In Laravel 5.5, they re-installed Whoops and redid the whole Exception-logic.

If we look at an error occurred, we always see the same line of code as faulty code.

![bugsnag](https://user-images.githubusercontent.com/6095391/30210767-1d3498fe-949e-11e7-90e7-e13707ca26e1.PNG)

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch.

> In Laravel 5.5, they re-installed Whoops.

That shouldn't make any difference to the reporting process. :)

> If we look at an error occurred, we always see the same line of code as faulty code and the stackstrace is missing.

That is something that is unique to parse errors I think. What happens in your app for other exceptions?

**Comment by dennisoderwald** [comment]
@GrahamCampbell I have the same problem in a freshly installed Laravel 5.5 application.

As a workaround, I replaced the report function in the exception handler (credits to @themsaid), and it works again:
```
    /**
     * Report or log an exception.
     *
     * This is a great spot to send exceptions to Sentry, Bugsnag, etc.
     * @TODO This whole method could be removed after bugsnag solve the breaking change in laravel 5.5
     *
     * @param  \Exception  $exception
     * @return mixed
     */
    public function report(Exception $exception)
    {
        if ($this->shouldntReport($exception)) {
            return;
        }

        if (method_exists($exception, 'report')) {
            return $exception->report();
        }

        try {
            $logger = $this->container->make(LoggerInterface::class);
        } catch (Exception $exception) {
            throw $exception; // throw the original exception
        }

        $logger->error($exception, $this->context());
    }

**Comment by KillermenBE** [comment]
@GrahamCampbell 

@GrahamCampbell 

If I halt the program at the following of app/Exceptions/Handler.php in Laravel 5.5, it will show me where the exception occured and show the correct stackstrace.

```
public function report(Exception $exception)
    {
        parent::report($exception);
    }
```

If I halt the program in the Bugsnag-php package on stackstrace.php at this line of code, I always get the same stackstrace (The ExceptionHandler, Pipelines and Middleware).

```
public static function generate(Configuration $config)
    {
        // Reduce memory usage by omitting args and objects from backtrace
        $backtrace = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS & ~DEBUG_BACKTRACE_PROVIDE_OBJECT);
        return static::fromBacktrace($config, $backtrace, '[generator]', 0);
    }
```

**Comment by aaronhuisinga** [comment]
Just want to confirm we're seeing the same issue in a production Laravel 5.5 application. @KillermenBE is correct.

**Comment by aaronhuisinga** [comment]
@GrahamCampbell would you or someone from the Bugsnag team be able to confirm this?
Since updating to Laravel 5, Bugsnag is basically not usable for debugging as we aren't able to view any sort of accurate traces.

**Comment by GrahamCampbell** [comment]
I am not able to simulate these issues? I have a Laravel 5.5 application, and it works?

**Comment by aaronhuisinga** [comment]
@GrahamCampbell I'm not certain how it's working properly for you. I've just done the following to make sure I'm not crazy and it's actually not functioning properly.

1) Created new Laravel 5.5 project.
2) Installed Bugsnag as a dependency, and followed along with the official Bugsnag Laravel installation guide (I used the multi logger).
3) Ran PHP artisan serve.
4) Changed the view() method for the welcome route to viefw() to throw an Exception.

Again, I'm seeing the only thing in my trace is the Handler.php file throwing an exception. I've uploaded a screenshot here: [https://imgur.com/a/a9SCE](https://imgur.com/a/a9SCE)

**Comment by TomKita** [comment]
@GrahamCampbell To confirm @aaronhuisinga statement above this is indeed a problem with the multilogger. lt this has to do with the changes done to the handler in laravel.

Specifically here`Handler.php:113, App\Exceptions\Handler->report()`

```
$logger->error(
            $e->getMessage(),
            array_merge($this->context(), ['exception' => $e]
        ));
```

The exception in laravel 5.5 is pushed into `$context` instead of the `$message`. 
`BugsnagLogger.php:73, Bugsnag\BugsnagLaravel\LaravelLogger->log()` expects the `$message` parameter to contain the exception not the context.

I can patch this just not sure what approach to take since this is a breaking change. We can grab the exception from the `$context` or do we tag this release as 3.0 and laravel 5.5+? 

I lean towards checking if the context holds the exception and moving it to the `$message` variable here: `MultiLogger.php:38, Bugsnag\BugsnagLaravel\MultiLogger->log()`. 

P.S. @GrahamCampbell Thanks for all that you do for Laravel!

**Comment by adiachenko** [comment]
I have the same issue after following official guide for integrating Bugsnag into Laravel 5.5 application.

**Comment by LasseRafn** [comment]
Same issue as well. Will look into this later

**Comment by kattrali** [comment]
I have a non-breaking fix, which would be to check if `$context['exception']` is set before attempting to coerce the message into an exception. I'll add a PR so we can all discuss there.

**Comment by LasseRafn** [comment]
Clever!
