### ISSUE TITLE
Auto Discovery support for Laravel 5.5

### ISSUE THREAD

**Issue by robbydooo** [bugsnag/bugsnag-laravel#255]
HI,

Can we add auto discovery to support Laravel 5.5 please?

Thanks,
Rob

**Comment by Cawllec** [comment]
Hi Rob,

We've got a PR for this - [#253](https://github.com/bugsnag/bugsnag-laravel/pull/253), but as Graham mentions on that PR it's not quite as simple as adding it in.  We need the Bugsnag provider to load earlier than the AppServiceProvider as it's required for the logger bindings.

There's a possibility we can add this in the future by removing the dependency on the Laravel logging service.

It may be worth directing further conversation to the linked PR.

Thanks,
Alex

**Comment by robbydooo** [comment]
Ok great thanks for the update. We have had similar issues with ordering or packages being an issue so understand there is a problem there right now.

**Comment by piperone** [comment]
Has there been any progress on this?
