### ISSUE TITLE
How to get release stages to notify when they are dynamically set?

### ISSUE THREAD

**Issue by AndreiaMatiasSilva** [bugsnag/bugsnag-laravel#262]
Hello,
I need to read the current notifyReleaseStages after being set with Bugsnag::setNotifyReleaseStages method. What's the way to do it?

Thanks in advance

**Comment by Cawllec** [comment]
There isn't currently a method for retrieving the NotifyReleaseStages from the Bugsnag client, but that's something that would definitely be worth adding in.

As for retrieving the release stages, if you're setting them through configuration can you retrieve it from there using:
```php
$config = $app->config->get('bugsnag');
if (isset($config['notify_release_stages'])) {
    $releaseStages = config['notify_release_stages']);
} 
```
?

**Comment by AndreiaMatiasSilva** [comment]
Thank you @Cawllec, I'll close the issue then
