### ISSUE TITLE
PHP 7 "Call to undefined method" error

### ISSUE THREAD

**Issue by vanrijs** [bugsnag/bugsnag-laravel#263]
Hi,

We upgraded today to PHP 7. Now i get this issue:
PHP Fatal error:  Uncaught Error: Call to undefined method Bugsnag\BugsnagLaravel\Facades\Bugsnag::notifyException()

Still running "bugsnag/bugsnag-laravel": "^2.0", so no further changes.

Is this a know issue?

**Comment by Cawllec** [comment]
Hi @vanrijs, are you still getting this issue?  Has the above issue solved anything for you?

**Comment by mverma16** [comment]
I am facing the same issue. Does anybody have a solution for this?

**Comment by tomlongridge** [comment]
@mverma16 - the notifier is tested against PHP 7 versions and works in a basic example. Can you confirm that you're using the latest bugsnag-laravel release; the version of Laravel you're using; and if possible provide some sort of reproducing project or instructions?

**Comment by mverma16** [comment]
@tomlongridge I checked further and I got it working. But I am still getting the same error when my application is unable to connect to the database. I updated database details in my .env with wrong credentials and tried to log the exception on Bugsnag but it did not notify  and in error logs I have
```PHP Fatal error: Uncaught Error: Call to undefined method Bugsnag\BugsnagLaravel\Facades\Bugsnag::notifyException()```

**Comment by tomlongridge** [comment]
If I adapt the example/laravel56 project to have some database access and then break the credentials in `.env` then I get a Bugsnag reported. Please can you try the same and compare the setup with your own project?

**Comment by mverma16** [comment]
Sure, I will try and update if it persists.
