### ISSUE TITLE
Support Laravel 5.5 Package Discovery

### ISSUE THREAD

**Issue by finalgamer** [bugsnag/bugsnag-laravel#266]
Add this to composer.json to make the package register the service provider and facade automatically.

composer.json
```
"extra": {
    "laravel": {
        "providers": [
            "Bugsnag\\BugsnagLaravel\\BugsnagServiceProvider"
        ],
        "aliases": {
            "Bugsnag": "Bugsnag\\BugsnagLaravel\\Facades\\Bugsnag"
        }
    }
},
```

**Comment by Cawllec** [comment]
Hi @finalgamer, thanks for the suggestion.  Unfortunately as we need our package to register before the `AppServiceProvider` we can't rely on package discovery.  Potentially this could be something we would support in the future.

**Comment by kattrali** [comment]
Closing as duplicate of #236 and [more](https://github.com/bugsnag/bugsnag-laravel/search?q=auto-discovery&type=Issues&utf8=%E2%9C%93)
