### ISSUE TITLE
more detail in breadcumbs

### ISSUE THREAD

**Issue by ludk17** [bugsnag/bugsnag-laravel#267]
show parameters sended in queries currently only show the "?" symbol and we can't know what parameters try to send.

### Expected behavior
**sql** select * from `users` where `status` = ? and email = ?
**params** "available", "email@email.com"
**time** 0.46ms
**connection** mysql

### Observed behavior
**sql** select * from `users` where `status` = ? and email = ?
**time** 0.46ms
**connection** mysql

### Version
*[2.5]*

**Comment by GrahamCampbell** [comment]
This is because the bindings recording is disabled by default. You can enable it to capture them.

**Comment by GrahamCampbell** [comment]
In `.env`:

```
BUGSNAG_QUERY_BINDINGS=true
```

**Comment by GrahamCampbell** [comment]
Example from one of my apps with this feature turned on:

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/2829600/33235731-e452be04-d236-11e7-97b3-bc388c5538cb.png">

**Comment by ludk17** [comment]
great thanks
