### ISSUE TITLE
Allow addMetaData() to append data at multiple points

### ISSUE THREAD

**Issue by bkuhl** [bugsnag/bugsnag-laravel#268]
I've encountered several scenarios where I'd like for different steps in my code to append a new "Tab" of data to the Bugsnag GUI.  Currently there's only a `setMetaData()` so it must all be done at once.  It'd be very useful to see an `addMetaData()` that appends to any existing data, or overwrites a given key.

**Comment by GrahamCampbell** [comment]
Thanks for the suggestion. The original design decision was to avoid bloating the API, since insertion can still be achieved using those methods.

**Comment by bkuhl** [comment]
I can understand that mentality.  Though I'd appreciate some consideration given to this anyways given the pretty much zero overhead associated with adding such a method.

**Comment by kattrali** [comment]
Adding a method to merge metadata makes sense to me too. Working with the metadata object can be cumbersome if you're doing more than setting an entire tab at once, and in other bugsnag libraries we've started to adopt a pattern similar to `addMetaData()` to merge data as a convenience.

**Comment by bkuhl** [comment]
Just FYI: Currently it looks like `setMetaData()` accepts a boolean `$merge` option as a second parameter.

`setxxxxx()` methods usually don't append, so this led to me having massive arrays of data going to Bugsnag as part of the context.

**Comment by Cawllec** [comment]
Closing this as fixed, let me know if there are any more issues @bkuhl
