### ISSUE TITLE
Class Query executed does not exist

### ISSUE THREAD

**Issue by danijelk** [bugsnag/bugsnag-laravel#269]
Not sure this has been reported before, but we're using some new profiling tools and are seeing this beeing reported as a 'problem'. 
It's not a critical one as it's captured by a try/catch. But I'm wondering why it's even trying to lookup something like 'query executed'?

> Message:
Class Query executed does not exist
Stacktrace:
ReflectionClass.__construct
/srv/www/vhosts/deployer/master/releases/123/vendor/bugsnag/bugsnag/src/Client.php:205
Bugsnag\Client.leaveBreadcrumb
/srv/www/vhosts/deployer/master/releases/123/vendor/bugsnag/bugsnag-laravel/src/BugsnagServiceProvider.php:87
Bugsnag\BugsnagLaravel\BugsnagServiceProvider.Bugsnag\BugsnagLaravel\{closure}
/srv/www/vhosts/deployer/master/releases/123/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:349
Illuminate\Events\Dispatcher.Illuminate\Events\{closure}
/srv/www/vhosts/deployer/master/releases/123/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php:200
Illuminate\Events\Dispatcher.dispatch
/srv/www/vhosts/deployer/master/releases/123/vendor/laravel/framework/src/Illuminate/Database/Connection.php:825
Illuminate\Database\Connection.event
/srv/www/vhosts/deployer/master/releases/123/vendor/laravel/framework/src/Illuminate/Database/Connection.php:682
Illuminate\Database\Connection.logQuery
/srv/www/vhosts/deployer/master/releases/123/vendor/laravel/framework/src/Illuminate/Database/Connection.php:635
Illuminate\Database\Connection.run
/srv/www/vhosts/deployer/master/releases/123/vendor/laravel/framework/src/Illuminate/Database/Connection.php:333
Illuminate\Database\Connection.select
/srv/www/vhosts/deployer/master/releases/123/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:1705

**Comment by Cawllec** [comment]
Hi @danijelk,

The Laravel notifier registers a listener for queries by default to create breadcrumbs from these queries, making it easier to track down root causes of issues.  This behaviour can be disabled by setting the environment variable `BUGSNAG_QUERY` to false in the application configuration.

As for the reason the exception is being caught, the code in `leaveBreadcrumb` attempts to get a more legible class name from a given class name.  As the given name `"Query executed"` isn't a class name, the `ReflectionClass` constructor throws an exception which we suppress.  This shouldn't have an impact on the operation of Bugsnag.

**Comment by danijelk** [comment]
Great just what I was hoping for. Will close the issue, thanks for the detailed explanation.
