### ISSUE TITLE
Errors not sent to Bugsnag from Log::error() in Laravel 5.2

### ISSUE THREAD

**Issue by mnimants** [bugsnag/bugsnag-laravel#270]
Hi!

### Expected behavior
Laravel Logs sent to bugsnag.

### Steps to reproduce

Laravel 5.2, bugsnag/bugsnag-laravel v2.7.0
I have these 2 lines in AppServiceProvider
`$this->app->alias('bugsnag.multi', \Illuminate\Contracts\Logging\Log::class);
  $this->app->alias('bugsnag.multi', \Psr\Log\LoggerInterface::class);`

When I throw the exception, error is sent to Bugsnag and everything is fine. It's not the case with Laravel logs when called with e.g. `Log::error("test error")`. I also tried the same setup for my Laravel 5.4. app and logs appear on Bugsnag. 

Has anyone else encountered this on Laravel 5.2 and know the fix?

**Comment by Cawllec** [comment]
Hi @mnimants, I'm investigating this and will let you know if I find any fixes.  Out of interest, what version of Bugsnag are you using with your 5.4 app?

**Comment by mnimants** [comment]
@Cawllec 
laravel/framework -> v5.4.23
bugsnag/bugsnag -> v3.6.0        
bugsnag/bugsnag-laravel -> v2.7.0
bugsnag/bugsnag-psr-logger -> v1.1.0

**Comment by mnimants** [comment]
Hi! Any updates on this?

**Comment by Cawllec** [comment]
So calling a log functions through the `Log` facade actually calls into the `Illuminate\Log\Writer Object` that seems to ignore the alias done earlier on.  I'd suggest writing to the application logger directly if you wish it to report exceptions to Bugsnag.
I'll have a look at how this behaviour can be changed to respect the aliases.

**Comment by GrahamCampbell** [comment]
What `Log` are you calling. This should be `Illuminate\Support\Facades\Log`, and not `Illuminate\Contracts\Logging\Log`.

**Comment by Cawllec** [comment]
I've been testing it with both and the results appear the same.

**Comment by adiachenko** [comment]
> I'd suggest writing to the application logger directly if you wish it to report exceptions to Bugsnag.

@Cawllec What do you mean? I tried to access LogManager directly via the container, it still doesn't send messages to Bugsnag.

So my question is, how do you actually make it work?

**Comment by Cawllec** [comment]
We've had a release since this issue was last updated, so I'll close this for now, but if the issue reoccurs please post back here.
