### ISSUE TITLE
Setting up bugsnag - defaults missing

### ISSUE THREAD

**Issue by simplenotezy** [bugsnag/bugsnag-laravel#282]
### Expected behavior
Show what the defaults is in bugsnag.php

### Observed behavior
I have to figure out myself what the defaults do. E.g. what happens if I don't set `notify_release_stages`? Will it notify on ALL stages? Or none?

### Steps to reproduce
Follow install instructions

### Additional information
I have followed installation guide from https://docs.bugsnag.com/platforms/php/laravel/#installation.

But I errors do not show up in bugsnag interface, e.g. trying to force an undefined variable, the error shows up in `laravel.log` but not bugsnag.

If I run `\Bugsnag::notifyError('ErrorType', 'Test Error');` it works though.

UPDATE: Error now shows up in bugsnag interface. It just took some time. Configurations (bugsnag.php) file is still confusing though. Lacking examples of what is default.

**Comment by Cawllec** [comment]
Hi @simplenotezy, thanks for the feedback, glad errors started showing up.  I'll make a note to review the documentation and clarify anything that doesn't seem to give an indication of default behaviour.
