### ISSUE TITLE
setMetaData() merging data between jobs

### ISSUE THREAD

**Issue by bkuhl** [bugsnag/bugsnag-laravel#283]
### Expected behavior
Metadata not being overriden with subsequent queue job calls.  So my custom tab should have a single game's id and name.

### Observed behavior
All game ids and names are appended to each call, leading to more metadata than should be called.
<img width="611" alt="screen shot 2018-01-11 at 1 11 07 pm" src="https://user-images.githubusercontent.com/524933/34839814-f1d77d44-f6d0-11e7-83a9-57275861068c.png">

### Steps to reproduce
Create a Laravel project with Horizon.  On the queue job, use similar code to the following:

```
    public function handle()
    {
        Bugsnag::registerCallback(function (Bugsnag\Report $report) {
            $report->setMetaData([
                'game' => [
                    'id' => $this->gameId(),
                    'name' => $this->game()->name,
                ],

                // This tells Bugsnag to overwrite the previous metadata.  Since queue workers
                // perform work for pretty much all games, we have to overwrite previous contexts
                // to ensure we get a single game's data
                false
            ]);
        });
```

Queue up a few jobs and let the same worker process this job with varying metadata.

### Version
v2.11.1

**Comment by Cawllec** [comment]
Hey @bkuhl, you've set the `merge` parameter inside of the array, meaning it's not being passed to the function and the callbacks are all merging their data.

Try:
```
$report->setMetaData([
    'game' => [
        'id' => $this->gameId(),
        'name' => $this->game()->name,
    ],
], false);
```

**Comment by Cawllec** [comment]
Alternatively you can use the `addMetaData` function, which overwrites by default.

**Comment by bkuhl** [comment]
:facepalm: oh my.... Thanks!
