### ISSUE TITLE
Call to undefined method Bugsnag\PsrLogger\MultiLogger::useFiles()

### ISSUE THREAD

**Issue by Teerr** [bugsnag/bugsnag-laravel#292]
Hello, I have a laravel project in which I need to log errors in two ways:
1. using Bugsnag
2. saving callstacks to separated files

In `register` method of `AppServiceProvider` I have:
```php
if (app()->environment('production')) {
    $this->app->alias('bugsnag.multi', \Illuminate\Contracts\Logging\Log::class);
    $this->app->alias('bugsnag.multi', \Psr\Log\LoggerInterface::class);
}
```

In `report` method of `\App\Exceptions\Handler` I have:
```php
\Log::useFiles(storage_path("logs/{$UID}.log"));
\Log::error($exception);
```

### Expected behavior
File with error is created and at the same time sent to Bugsnag.

### Observed behavior
I get error:
```"Call to undefined method Bugsnag\PsrLogger\MultiLogger::useFiles()"```

but should be called ```\Bugsnag\BugsnagLaravel\MultiLogger::useFiles()```

### Version
The error occured after updating:
```
bugsnag/bugsnag (v3.11.0 => v3.12.0) 
bugsnag/bugsnag-psr-logger (v1.4.0 => v1.4.1)      
bugsnag/bugsnag-laravel (v2.12.0 => v2.14.0)
```

### Additional information
I followed and re-checked instructions [here (installation)](https://docs.bugsnag.com/platforms/php/laravel/#installation)

**Comment by GrahamCampbell** [comment]
What version of Laravel are you using please?

**Comment by Teerr** [comment]
It is version 5.4

**Comment by Cawllec** [comment]
Hi @Teerr, I've found what the issue is and will be adding a fix shortly.

**Comment by Cawllec** [comment]
With the release of 2.14.1 this issue should now be fixed.
