### ISSUE TITLE
does this work alongside arcanedev/log-viewer ?

### ISSUE THREAD

**Issue by vesper8** [bugsnag/bugsnag-laravel#296]
I installed bugsnag because I wanted to get notified when there are serious errors. But I noticed that ever since I added bugsnag my laravel log files are no longer populated

that is.. I have a lot of \Log::debug() and \Log::info() calls throughout my application and none of these are going to my log files anymore

This is very much unwanted.. I want my internal logging to continue working as it had before + have actual errors goto Bugsnag.. how can I have both?

**Comment by snmaynard** [comment]
I am answering on your support ticket so closing this one out.
