### ISSUE TITLE
Class bugsnag does not exist  

### ISSUE THREAD

**Issue by Donkfather** [bugsnag/bugsnag-laravel#297]
### Expected behavior
When `php artisan` is run it should show a list of all commands 

### Observed behavior
When ran `php artisan` i got an error 
```
In Container.php line 752:
                                
  Class bugsnag does not exist 
```

### Steps to reproduce
Set APP_ENV to anything but `local`

### Version
laravel/framework 5.5.39
bugsnag/bugsnag-laravel 2.4.3

**Comment by GrahamCampbell** [comment]
Have you registered the service provider in config/app.php?

**Comment by ryantbrown** [comment]
I am having this same issue and it just started happening. Locally it works but production I get the same error.

**Comment by Donkfather** [comment]
@GrahamCampbell yes. If APP_ENV is set to `local` it works no problem. If I set it to anything else .. I get the error. But from playing around I think that the error is only in artisan. not sure ..

**Comment by Cawllec** [comment]
Hi @Donkfather, can you verify the Bugsnag-laravel version?  We haven't released a v2.4.3 of Bugsnag-laravel.

**Comment by njxqlus** [comment]
Same bug. 
APP_ENV=local
Laravel 5.6.15
Bugsnag 2.14.1

Steps: 
```php
public function report(Exception $exception)
{
    Bugsnag::notifyException($exception);
    parent::report($exception);
}
```

Composer.json:
```js
   "require": {
        "php": "^7.1.3",
        "bugsnag/bugsnag-laravel": "^2.0",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "^1.0",
        "yajra/laravel-oci8": "5.6.*"
    },
    "require-dev": {
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0",
        "barryvdh/laravel-ide-helper": "^2.4"
    },
```

**Comment by GrahamCampbell** [comment]
You shouldn't need to call notifyException if the logging is setup properly.

**Comment by Cawllec** [comment]
@njxqlus, have you set up the facade alias:
`'Bugsnag' => Bugsnag\BugsnagLaravel\Facades\Bugsnag::class,`
in your class Aliases array in `config/app.php`?

**Comment by njxqlus** [comment]
@GrahamCampbell I tried to call Exception without notifyException in Handler, nothing happened.
@Cawllec I follow instruction in my panel, there are nothing about that, but now I added alias. Nothing changed: if I try to `Bugsnag::notifyException` from my controller `Class bugsnag does not exist` error appear

**Comment by Cawllec** [comment]
Have you followed the steps about setting up logging [here](https://docs.bugsnag.com/platforms/php/laravel/#laravel-5-6)?

**Comment by njxqlus** [comment]
@Cawllec yes, my `logging.php` looks like this:
```php
    'channels' => [
        'stack' => [
            'driver'   => 'stack',
            'channels' => ['single', 'bugsnag'],
        ],

        'bugsnag' => [
            'driver' => 'bugsnag',
        ],
```

**Comment by GrahamCampbell** [comment]
Can you run `php artisan tinker` and then `config('app.providers');` please and show us the output?

**Comment by njxqlus** [comment]
@GrahamCampbell yes, this is my error. I have the habit that laravel packages are auto adding to providers

**Comment by Cawllec** [comment]
Closing this for now, @Donkfather if you have any more information please let us know and I'll re-open this.

**Comment by synergixe** [comment]
This is a huuge bug now... I can't even use BugSnag at all.

I have tried everything I know in Laravel-Land and still no respite

I have the same exact Laravel version as @nxjqlus

**Comment by Cawllec** [comment]
Hi @synergixe, have you tried the same solution, ensuring the Bugsnag provider is correctly added to your `appServiceProvider`?  If that doesn't work, could you open a new issue for this please?

**Comment by musa11971** [comment]
Was experiencing this problem in production environment, but not locally.

Running the following commands on production fixed it:
```bash
cd bootstrap/cache/
rm -rf *.php
```

**Comment by JavierSolis** [comment]
In addition to @ musa11971 I copied the bugsnag.php file in folder config manually and defined the variables in the .env file, so finally I could fix it. u.u

**Comment by arm092** [comment]
I just add Bugsnag to providers list, and problem solved
