### ISSUE TITLE
Severity level default for exceptions should be 'error', not 'warning'

### ISSUE THREAD

**Issue by gregrobson** [bugsnag/bugsnag-laravel#30]
I'm customising my own authentication exceptions as they have a lesser priority that fatal/halting code exceptions (it's normally because people are not logged in, or they are trying things they don't have access to, it's nice to keep an eye on, but normally cause for concern) and after reading the code and docs, it appears that "severity" definitions are not inline with what I have seen in other applications.

Laravel and it's related packages (Monolog) follow the RFC5424 which defines the error levels as follows http://en.wikipedia.org/wiki/Syslog#Severity_levels
Based on this I would expect:

* **Errors** to be PHP Exceptions for: divide by 0, syntax errors, null when resource expected
* **Warnings** to be what I customise for login failures, 401/403 HTTP statuses that I send out. Worth noting, but not requiring prompt attention.

Currently it appears that Bugsnag sends *warning* (not *error*) by default (and by design)? There may be a reason for this I have overlooked, but I think it makes more sense to tell me it's an error as the application has stopped working!

I can use `setBeforeNotifyFunction()` to check the class name and set severity as required, however I thought you might want to know that it doesn't quite match up to other packages.

**Comment by ConradIrwin** [comment]
Thanks! you're totally right :).

Conrad
