### ISSUE TITLE
It triggers MessageLog event 3 times

### ISSUE THREAD

**Issue by lezhnev74** [bugsnag/bugsnag-laravel#306]
### Expected behavior
I want to see just one message in browser:
```
Event caught: Route / opened
``` 

### Observed behavior
I see three messages in browser:
```
Event caught: Route / opened
Event caught: Route / opened
Event caught: Route / opened
```

### Steps to reproduce
- install laravel 5.5
- install bugsnag-laravel (latest version)
- follow [installation instructions](https://docs.bugsnag.com/platforms/php/laravel/#installation)
   As it says: `If you’d like to keep logging to your original logger as well as Bugsnag, you can bind 'bugsnag.multi' rather than 'bugsnag.logger'`. I want to be able to log my messages to text log as well as to bugsnag.
- in `app/Providers/AppServiceProvider.php`:

```php
<?php

namespace App\Providers;

use Illuminate\Log\Events\MessageLogged;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->app->alias('bugsnag.multi', \Illuminate\Contracts\Logging\Log::class);
        $this->app->alias('bugsnag.multi', \Psr\Log\LoggerInterface::class);
    }

    public function register()
    {
        // I need to listen to this event
        \Event::listen(MessageLogged::class, function (MessageLogged $event) {
            echo "Event caught: $event->message \n";
        });
    }
}
```
- I added a web route like this in `routes/web.php`:
```php
Route::get('/', function () {
    \Log::info("Route / opened");
});
```
- run local server from the root folder of the project (php 7.2):
`php -S 0.0.0.0:8821 -t public`
- open home page in browser: http://127.0.0.1:8821

### Version
2.14.1 (latest at the moment)
php 7.2
laravel 5.5

### Comments
File `src/EventTrait.php` has the logic responsible for that. As I understand, when the BugsnagLogger is combined with the built-in Laravel logger both fire this event. Thus one cannot reliably listen to the event since it can be fired multiple time for the same message.

**Comment by Cawllec** [comment]
Hi Hi @lezhnev74, this seems to be an issue with our latest implementation.  The default `MultiLogger` contains 3 sub-loggers: the apps `log`, the base `bugsnag.logger`, and the apps `events` logger.  The `bugsnag.logger` contains a further two targets - the `bugsnag` instance, and the apps `events` logger again.

It seems we're logging a message to the apps `log`, and dispatching two messages through the apps `events` logger, creating three MessageLogged events total.  I need to verify this and discuss a course of action with colleagues for now, but thanks for bringing this up.  I'll update you when a solution or action is determined.

**Comment by craftyshaun** [comment]
Hi @Cawllec have you made any progress on this bug? 

We are also seeing this on the `\Log::listen(...)` function as well which most likely uses the same event hooks.

**Comment by lezhnev74** [comment]
I must say that my project [apideveloper.io](https://apideveloper.io) is highly affected by this issue (this service logs all messages to the external storage and I observe multiple entries as a result). If you can increase the priority of this subject that would be most appreciated!

**Comment by lezhnev74** [comment]
Happy new year! 🌴 Can you refresh the state of this issue?

**Comment by Cawllec** [comment]
Hey guys, we've bumped up the priority of this and will be getting to it ASAP.  Thanks for your patience.

**Comment by lezhnev74** [comment]
Nice to hear to you are tackling this! 

Based on your response, does it mean that this code will echo twice?
```
\Event::listen(MessageLogged::class, function (MessageLogged $event) {
    echo "Event caught: $event->message \n";
});
```
