### ISSUE TITLE
FatalErrorException gets sent twice

### ISSUE THREAD

**Issue by gregrobson** [bugsnag/bugsnag-laravel#31]
I was just testing some changes I have made and I noticed that when a fatal syntax error occurs and a `Symfony\Component\Debug\Exception\FatalErrorException` is thrown Bugsnag is notified twice?

These errors wouldn't make it into our production code of course :wink: I just thought you might want to know in case that's something you need to be aware of.

**Comment by snmaynard** [comment]
Closing as we have merged a fix!
