### ISSUE TITLE
Using a custom middleware will show up as the primary source of all reported exceptions in bugsnag

### ISSUE THREAD

**Issue by dsge** [bugsnag/bugsnag-laravel#312]
### Expected behavior
When an exception occurs in laravel's `/app` folder (but not in the middleware itself) I would expect Bugsnag to open the stacktrace at the source of the exception (e.g. at the line that has `throw new Exception()`).

In other words, I would expect Bugsnag to treat `routes/web.php:15` as the source of the exception, like this:
![image](https://user-images.githubusercontent.com/5737250/43961155-76718e80-9cb4-11e8-91ed-9144f0ae3338.png)

### Observed behavior

Bugsnag treats every exception in my app as if it's the middleware's fault.

The UI always opens here:
![image](https://user-images.githubusercontent.com/5737250/43961345-f7c92100-9cb4-11e8-8555-260e1f119cd3.png)

The notification emails always contain `app/Http/Middleware/LegacyUserAuthMiddleware.php:47`:
![image](https://user-images.githubusercontent.com/5737250/43961382-1deec100-9cb5-11e8-86bb-3247a50c2c0b.png)

### Steps to reproduce

- Create a middleware somewhere in your `/app` folder
- Implement a `handle($request, $next)` function in it that simply contains `return $next($request);` (so it basically doesn't do anything)
- Add this middleware to your global middleware stack
- Call a route that throws an Exception
- Notice that your `return $next($request);` line is now treated by bugsnag as the primary source of your Exception instead of accusing your route as being the primary source

### Version

```
bugsnag/bugsnag                       v3.12.1 Official Bugsnag notifier for PHP applications.
bugsnag/bugsnag-laravel               v2.14.1 Official Bugsnag notifier for Laravel applications.
bugsnag/bugsnag-psr-logger            v1.4.1  Official Bugsnag PHP PSR Logger.
laravel/framework                     v5.5.40 The Laravel Framework.
```

#### The stacktrace itself contains the correct information
Clicking on the "Full Trace" button on bugsnag.com's UI correctly displays the stack trace and it correctly has the "real" source of the Exception at the top of the stacktrace.

#### My guess on why this happens

As I understand my problem happens because for bugsnag my middleware is "in the project" and since in Laravel 5.5 a middleware is technically the last code that runs in my app - hence Bugnsag thinking that the middleware has to be what threw an exception.

#### Why doesn't is happen to the default middlewares that laravel itself puts in the `app` folder?

Laravel's Http Kernel also has other middlewares that are in the `app` folder like `\App\Http\Middleware\TrustProxies`. The difference between the TrustProxies middleware and my middleware is that TrustProxies inherits it's `handle()` function from it's parent and does not override it. If it were to override it then it would behave in bugsnag reports as my custom middleware does.

#### Possible hotfix that I can't see the side effects of

I _could_ override `Bugsnag\Configuration::isInProject()` to basically treat my custom middlewares as 3rd party code but since my middlewares could (in theory) throw "real" Exceptions that might show up as some random other code piece threw them.

**Comment by snmaynard** [comment]
In this case you want to set the inproject to false. If you do that, it will only group on the very top line of the stacktrace when all lines are out of project - which I think is what you are asking for.

**Comment by GrahamCampbell** [comment]
You could also:

1. Define your routes from somewhere within the `app` folder so that Bugsnag thinks they're project code, like in the example project (https://github.com/bugsnag/bugsnag-laravel/blob/master/example/laravel/app/Http/routes.php and https://github.com/bugsnag/bugsnag-laravel/blob/master/example/laravel/app/Providers/RouteServiceProvider.php#L45-L60).

or

2. Tell Bugsnag the routes folder is project code, Bugsnag::setProjectPath can take regex to match as well as just a string prefix (https://github.com/bugsnag/bugsnag-php/blob/v3.14.1/src/Configuration.php#L255-L269).

**Comment by dsge** [comment]
Thanks for your answers. I ended up overriding `Bugsnag\Configuration::isInProject()` so that it excludes my middlewares and includes my routes (I didn't even realize that the routes were not included) but otherwise it maintains previous functionality. 

> Bugsnag::setProjectPath can take regex to match as well as just a string prefix (https://github.com/bugsnag/bugsnag-php/blob/v3.14.1/src/Configuration.php#L255-L269).

As far as I can tell `$projectRoot` cannot be a regex there. And the resulting `$this->projectRootRegex` cannot be modified from the outside. But it would be a nice feature :)

Anyway the resulting exception notifications are now looking as expected:
![image](https://user-images.githubusercontent.com/5737250/44033472-c4fa6614-9f0a-11e8-81e9-23807a9e6dc9.png)

Thanks again :)
