### ISSUE TITLE
Cant make controller in luman

### ISSUE THREAD

**Issue by sarderiftekhar** [bugsnag/bugsnag-laravel#314]
I am trying to make a controller but getting this error.

C:\xampp\htdocs\gimo\gov2>php artisan make:controller netbetngController
  [ErrorException]
  Undefined index: HTTP_HOST

Can some one please help.

**Comment by GrahamCampbell** [comment]
Related to https://github.com/bugsnag/bugsnag-laravel/issues/68 perhaps?

**Comment by GrahamCampbell** [comment]
What version of Bugsnag's library are you using please? This looks a lot like the same issue I fixed a few years ago: https://github.com/bugsnag/bugsnag-php/pull/302.

Please could you run `composer show | grep 'bugsnag/\|laravel/'` from the directory of your project that contains the `composer.json` file. This will show us the versions of Bugsnsag and Laravel you have.

**Comment by Cawllec** [comment]
Hi @sarderiftekhar, I'm closing this for now.  If the issue reoccurs, or you've got some more information, we'll get it reopened.
