### ISSUE TITLE
How could I mark logs from different channels ?

### ISSUE THREAD

**Issue by smknstd** [bugsnag/bugsnag-laravel#317]
I use different logging channels in my laravel app. I log them all in bugsnag but it seems I'm unable to filter them then. Does anybody using channels ? How could I do that ?

thanx

**Comment by Cawllec** [comment]
Hi @smknstd, the suggested way would be to use [callbacks](https://docs.bugsnag.com/platforms/php/laravel/customizing-error-reports/#adding-callbacks).  I would be to add a callback in each channel identifying the channel in question, like:
```
Bugsnag::registerCallback(function ($report) {
        $report->setMetaData([
        'logging channel' => [
            'name' => 'channel 3'
        ]
    ]);
```
Then when a message from a particular channel is sent to Bugsnag, the channel name should appear as metadata.  You may have an issue if messages are being sent through multiple channels, as each callback will be trigged in the event of a notification, but you should still be able to filter through by channel.

**Comment by smknstd** [comment]
Hi @Cawllec, thanx for your quick answer. Adding metadata manually seems like a good idea, but I don't get how would I register a different callback for each channel. Do you have any idea ?

**Comment by smknstd** [comment]
Also, dashboard filtering based on the new metadata field would require a "Custom filter" which is only available on pro plan...

**Comment by snmaynard** [comment]
You could also use the context field which is filterable by default, but then you would lose the ability to filter based on what is in there right now.

**Comment by snmaynard** [comment]
You can use `report.setContext` from https://github.com/bugsnag/bugsnag-php/blob/master/src/Report.php#L454

```php
Bugsnag::registerCallback(function ($report) {
        $report->setContext('channel 3');
});
```

**Comment by smknstd** [comment]
Thanx for your help ! But I have the same problem as before... I don't get how would I register a different callback for each channel.

**Comment by snmaynard** [comment]
You can't. You'd have one callback and then you'd have to figure out which channel the log message came from. 

Depending on how you are hooking up the log channels you could do this as a part of the notify call (setting the context).

**Comment by smknstd** [comment]
My question was about laravel 5.6 logging channels https://laravel.com/docs/5.6/logging#writing-to-specific-channels, I can't set context specifically every time...

```
Log::channel('stripe')->error('Payment refused');
...
Log::channel('emailing')->error('Sending email failed');
```

**Comment by Cawllec** [comment]
Hi @smknstd, apologies for a reply taking so long.  Did you manage to get any further with this? Did you find a way to identify which channel a specific log came from inside a logger?

**Comment by Cawllec** [comment]
I'm going to close this issue for now, but if you have any more queries reply here and I'll get it reopened.
