### ISSUE TITLE
Laravel Strict Mode Errors aren't going to Bugsnag

### ISSUE THREAD

**Issue by gustavodebiasi** [bugsnag/bugsnag-laravel#340]
### Expected behavior
All errors to be reported in bugsnag

### Observed behavior
All strict mode unhandled errors aren't being reported to bugsnag

### Steps to reproduce
1 - Active strict Laravel Mode MySQL database
2 - create a non-nullable field in database
3 - try to save a record without any content in this field
4 - the error is reported in laravel log storage but not in bugsnag

### Version
^2.15

### Additional information
Someone knows if there's a configuration for that?

Thank you very much!

**Comment by gustavodebiasi** [comment]
> Interesting. It's odd that Laravel has logged it, but not Bugsnag. What version of Laravel are you using please?

I'm using Laravel 5.7


> My other question would be, how many events are you sending to Bugsnag per hour? Is it possible events are being sent but dropped because the plan limit has been exceeded?

I tought I could be this, but the problem is that I'm not receiving errors just from strict mode. The others I'm receiving.
In the same time, I tried again looking for the events usage (today was 18 events) and I tried to make the error again, on bugsnag didn't receive, but on laravel log yes.

![image](https://user-images.githubusercontent.com/15871743/51470232-747b2380-1d5a-11e9-9c8f-ae5b7d7d10fc.png)

`[2019-01-21 08:54:32] production.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'cliente' cannot be null (SQL: update `chats` set `cliente` = , `atendente` = , `updated_at` = 2019-01-21 08:54:32 where `id` = 15728) {"userId":1,"email":"gustavo@otimizy.com.br","exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'cliente' cannot be null (SQL: update `chats` set `cliente` = , `atendente` = , `updated_at` = 2019-01-21 08:54:32 where `id` = 15728) at D:\\sites\\samuelbasso\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:664, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'cliente' cannot be null at D:\\sites\\samuelbasso\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:483)
[stacktrace]`

**Comment by GrahamCampbell** [comment]
Hmmm. What does you log configuration look like please? Is the logging system trying to write to the database perhaps, and crashing before it gets around to calling Bugsnag?

**Comment by gustavodebiasi** [comment]
@GrahamCampbell I don't think so...

`'default' => 'stack',

    'channels' => [
        'stack' => [
            'driver' => 'stack',
            'channels' => ['daily', 'bugsnag'],
        ],

        'bugsnag' => [
            'driver' => 'bugsnag',
        ],

        'single' => [
            'driver' => 'single',
            'path' => storage_path('logs/laravel.log'),
            'level' => 'debug',
        ],

        'daily' => [
            'driver' => 'daily',
            'path' => storage_path('logs/laravel.log'),
            'level' => 'debug',
            'days' => 14,
        ],`

**Comment by Cawllec** [comment]
Hi @gustavodebiasi, I'm investigating this issue now, as we've had a similar report of QueryExceptions potentially not being notified.  I haven't been able to reproduce the issue in any of our example apps following your steps, so was hoping you'd be able to provide us with some more information to help narrow down what's happening.

It'd be useful to know:
- Where the failing query is occurring (i.e. middleware, controllers, jobs, etc..)
- Are you seeing the same result on different `APP_ENV`s, i.e. `development` vs `production`
- Are you using any plugins to access the database, or just the Laravel `DB` query constructor?

**Comment by Cawllec** [comment]
As an extra step, it would be really useful if you could present a reproduction case, such as a Laravel app in a git repo that will help to track down and fix the issue.

**Comment by gustavodebiasi** [comment]
Hi @Cawllec, no problem!

> Where the failing query is occurring (i.e. middleware, controllers, jobs, etc..)
On Controller

> Are you seeing the same result on different APP_ENVs, i.e. development vs production
Yes

> Are you using any plugins to access the database, or just the Laravel DB query constructor?
I'm using normal Model Database from Laravel

> Are other unhandled errors being reported to Bugsnag in the same environment where QueryExceptions are not?
Yes

About the Repo, I'll make it and after I'll send you.

**Comment by gustavodebiasi** [comment]
Hi @Cawllec and @GrahamCampbell , just found de problem.

I'm getting this error when the package is sending the error to Bugsnag:
`"json_encode error: Malformed UTF-8 characters, possibly incorrectly encoded"`

This problem is occuring because of my user object. I have some data that isn't utf-8 encoded.

Desabling the BUGSNAG_USER, Bugsnag reporting works fine.
But, I wanted to receive the user information to know with which customers I'm getting this error.

I tried to use bugsnag filters for don't send that no utf8 encoded information, but it doesn't affect user the maker (setUser()).

Do you have any advice of how I could solve this?

For now, I'm disabling user information. But maybe we could create a filter for user object or use the actual filter on this object.

Thank you!

**Comment by Cawllec** [comment]
Hi @gustavodebiasi I've raised a ticket to improve our support for payload filtering and sanitation in the PHP notifiers, and although I'm closing this ticket it'll get an update when we're implementing the necessary changes.  Thanks for your feedback.
