### ISSUE TITLE
PHP Fatal error:  Uncaught ErrorException: php_uname() has been disabled for security reasons in 

### ISSUE THREAD

**Issue by amineameur** [bugsnag/bugsnag-laravel#341]
[21-Jan-2019 15:55:54 UTC] PHP Fatal error:  Uncaught ErrorException: php_uname() has been disabled for security reasons in /home/lgavocat/public_html/myapp/vendor/bugsnag/bugsnag/src/Configuration.php:468
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'php_uname() has...', '/home/lgavocat/...', 468, Array)
#1 /home/lgavocat/public_html/myapp/vendor/bugsnag/bugsnag/src/Configuration.php(468): php_uname('n')
#2 /home/lgavocat/public_html/myapp/vendor/bugsnag/bugsnag/src/Report.php(625): Bugsnag\Configuration->getDeviceData()
#3 /home/lgavocat/public_html/myapp/vendor/bugsnag/bugsnag/src/HttpClient.php(181): Bugsnag\Report->toArray()
#4 /home/lgavocat/public_html/myapp/vendor/bugsnag/bugsnag/src/HttpClient.php(166): Bugsnag\HttpClient->build()
#5 /home/lgavocat/public_html/myapp/vendor/bugsnag/bugsnag/src/Client.php(385): Bugsnag\HttpClient->send()
#6 [internal function]: Bugsnag\Client->flush()
#7 {main}
  thrown in /home/lgavocat/public_html/myapp/vendor/bugsnag/bugsnag/src/Configuration.php on line 468

**Comment by amineameur** [comment]
my application turn on local but when i put it on server error_log shows me this can any one please help me

**Comment by Cawllec** [comment]
Hi @amineameur, this is likely due to the `disable_functions` setting of the servers `PHP.ini` containing `php_uname` by default, disabling that functionality.  If the `php_uname` entry can be removed, the library should work as expected.

In the meantime, I'll raise a suggestion to our products team to restrict this call in environments where it may be problematic.

**Comment by amineameur** [comment]
@Cawllec thank you :blush:
