### ISSUE TITLE
Wrong error logging in Jobs with latest laravel

### ISSUE THREAD

**Issue by Tlapi** [bugsnag/bugsnag-laravel#346]
### Expected behavior
Get full error log

### Observed behavior
ReflectionException artisan xxx:yyy
Method XXXX\YYYY::report() does not exist

### Version
bugsnag/bugsnag v3.16.0
laravel/framework v5.8.4

**Comment by mattdyoung** [comment]
Following this up via Bugsnag support as this looks specific to the errors being reported rather than a generic issue with Bugsnag and Laravel v5.8.4.
