### ISSUE TITLE
Log::warning messages are marked in bugsnag with severity error

### ISSUE THREAD

**Issue by pjeutr** [bugsnag/bugsnag-laravel#349]
### Expected behavior
When using Log::warning in an application, bugsnag will mark it with Severity = warning 

### Observed behavior
Log::warning messages have Severity = error (also see image)

### Version
bugsnag/bugsnag v3.16.0
bugsnag/bugsnag-laravel v2.15.2
bugsnag/bugsnag-psr-logger  v1.4.1 
laravel/framework v5.4.36
### Additional information
Not sure if this happens in this package or somewhere else in the bugsnag chain
No additional enviroment bugsnag variables are set in .env
Our aim is to set filter "Email notifications" severity to only error, at the moment warning messages are still delivered. 
Seeing Log Warning and Severity error in the following screenshot of a mail, seems proof something goes wrong.

![image](https://user-images.githubusercontent.com/611968/55023946-23a7d580-4ffe-11e9-9be3-8fdfe14e3dbb.png)

**Comment by tomlongridge** [comment]
This is now fixed by [v1.4.2](https://github.com/bugsnag/bugsnag-psr-logger/releases/tag/v1.4.2) release of the bugsnag-psr-logger. If you update the latest dependencies, warnings will now be correctly reported.
