### ISSUE TITLE
Support for Laravel5?

### ISSUE THREAD

**Issue by bcdennis** [bugsnag/bugsnag-laravel#35]
Are there plans to update this to support Laravel5?

**Comment by cameronja** [comment]
+1

**Comment by homoky** [comment]
+1

**Comment by VH0815** [comment]
+1

**Comment by gregrobson** [comment]
:+1:

**Comment by strebl** [comment]
:+1:

**Comment by gregrobson** [comment]
5.0 released! Bugsnag got mentioned in the new documenation :smile: 
http://laravel.com/docs/master/errors#handling-errors

**Comment by ConradIrwin** [comment]
Released in v1.3.0
