### ISSUE TITLE
Metadata not available when request is large

### ISSUE THREAD

**Issue by KKSzymanowski** [bugsnag/bugsnag-laravel#350]
### Expected behavior
Metadata is shown in Bugsnag dashboard

### Observed behavior
Metadata is not shown in Bugsnag dashboard

### Steps to reproduce
When an exception occurs when processing a large request no cookie, request or custom metadata is available. 

I have registered some custom metadata:
```php
Bugsnag::registerCallback(function ($report) {
    $report->setMetaData([
        'account' => [
            'name' => 'Acme Co.',
            'paying_customer' => true,
        ]
    ]);
});
```
and tested it on two requests:
**50kB request**
![image](https://user-images.githubusercontent.com/13980973/55874459-b6b24500-5b92-11e9-8e63-746de2891205.png)

**800kB request**
![image](https://user-images.githubusercontent.com/13980973/55874473-c2057080-5b92-11e9-94d6-82c07e19b575.png)

### Version
laravel/framework: 5.8.7
bugsnag/bugsnag-laravel: 2.15.2

**Comment by GrahamCampbell** [comment]
Thanks for the report. Very roughly, I think this is actually the expected behaviour. The server has a maximum payload size, so the client library will cut down on the metadata if it's too large.

Perhaps maybe the client library should be more intelligent about what it cuts. Is it the request body itself that's large?

**Comment by KKSzymanowski** [comment]
> Is it the request body itself that's large?
Yes, the request body ie. `CONTENT_LENGTH` was 57000 in the first example and 843000 in the second one.

**Comment by tomlongridge** [comment]
@KKSzymanowski - the limit on breadcrumb size has just been increased in bugsnag-php ([v3.18.0](https://github.com/bugsnag/bugsnag-php/releases/tag/v3.18.0)). If you update your dependencies, I believe this should by sufficient given the sizes quoted above.
