### ISSUE TITLE
Feature request: send Bugsnag reports asynchronous

### ISSUE THREAD

**Issue by rolfdenhartog** [bugsnag/bugsnag-laravel#368]
Hi,

I was wondering if there was a way to send reports asynchronous. I'm submitting the issue here, because there is a simple tool that can be used with Laravel: the Laravel queue (Horizon). The problem right now is that we have requests taking 200ms to respond. Which could be less than 100ms if Bugsnag was sending report in the background. My idea was to using the queue to do this.

I was looking at the code (including the `bugsnag/bugsnag-php` repo) and it seems that there should be a `QueueClient` or `LaravelClient` class (build on top of `HttpClient`?). For every report added, a job should be dispatched to send the data to Bugsnag.

I would like to help implementing this feature, but I'm sure where to start. Thanks anyway!

(my apologies for my English).

**Comment by mattdyoung** [comment]
Hi @rolfdenhartog 

This seems like a sensible feature for our PHP libraries to support. We already support asynchronous delivery on many of our other platform error reporting libraries.

We'd want to carefully design this to ensure a consistent approach across our libraries, so we'd be unlikely to accept a PR at this point.

We'll raise as a feature request on our backlog though to investigate when we have the bandwidth.

Thanks!

**Comment by imjoehaines** [comment]
Hey @rolfdenhartog

I recently looked at making our requests asynchronous with Guzzle's async capabilities, but hit an infinite loop (https://github.com/guzzle/guzzle/issues/2752) which wasn't possible to fix without a major refactor and breaking changes. Implementing a `QueueClient` also isn't really possible at the moment without major changes

We're looking at other ways to improve how we make HTTP requests, but it looks like this will need major changes to the bugsnag-php library. I'm closing this issue as we would ideally improve the situation for everyone, not just Laravel users, so hopefully there would be no need for a `QueueClient`

Thanks 🙂
