### ISSUE TITLE
Question: Won't the token expire when on a long running job if the Client is a signleton?

### ISSUE THREAD

**Issue by mathiasgrimm** [bugsnag/bugsnag-laravel#371]
### Expected behavior
*[Insert details on expected behaviour]*

### Observed behavior
*[Insert details on observed behaviour]*

### Steps to reproduce
*[Insert reproduction steps (if known)]*

### Version
*[Insert version information]*

### Additional information
*[Insert any additional information]*

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by rjharrison** [comment]
Hi Mathias. No it won't expire. Both the notifier API key and the data-access API token are fixed and will not expire. You can manually regenerate/delete them via the dashboard.
