### ISSUE TITLE
Wrong namespace of exception handler

### ISSUE THREAD

**Issue by VH0815** [bugsnag/bugsnag-laravel#38]
The namespace of the exception handler class seems to be hardcoded. Due to the PSR4 autoloader in L5 its best practice to rename the namespace of the app directory (http://laravel.com/docs/5.0/configuration#after-installation).

```
Fatal error: unknown class App\\Exceptions\\Handler in /usr/share/nginx/html/foo/bar/vendor/bugsnag/bugsnag-laravel/src/Bugsnag/BugsnagLaravel/BugsnagExceptionHandler.php on line 7
```

Handler.php is correctly namespaced, but wrong referenced in BugsnagExceptionHandler.php

```
use App\Exceptions\Handler as ExceptionHandler;
```

**Comment by adamgoose** [comment]
Yeah, this is for sure an issue, and likely going to be incredibly difficult to fix.

**Comment by adamgoose** [comment]
I was able to thwart this issue by doing the following:

1. NOT include the `BugsnagLaravelServiceProvider`
2. Using `php artisan make:provider BugsnagServiceProvider`
3. Editing this provider to include the same `register()` method as the shipped provider.
4. Updating my `App\Exceptions\Handler` (except it's not `App`), and replacing that `report()` method with the same `report()` method as the shipped handler.

**Comment by johnnygreen** [comment]
Also having this issue.  Should bugsnag extend Illuminate\Foundation\Exceptions\Handler instead?

**Comment by johnnygreen** [comment]
http://laravel.com/docs/5.0/errors#handling-errors

We can temp put this in the main handler
```
public function report(Exception $e)
  {
    $shouldReport = true;
    
    foreach ($this->dontReport as $type)
    {
        if ($e instanceof $type)
            $shouldReport = false;
    }

    if ($shouldReport) {
       $bugsnag = App::make('bugsnag');
       $bugsnag->notifyException($e);
    }
    
    return parent::report($e);
  }
```

**Comment by ConradIrwin** [comment]
I'd love feedback on #40 — would that work for everyone?
