### ISSUE TITLE
Cannot specify timeout

### ISSUE THREAD

**Issue by henrysearle** [bugsnag/bugsnag-laravel#390]
### Observed behavior
We had an issue at around March 4th 18:20 UTC where we had a lot of different services report a connection issue with Bugsnag and a few other services. Long story short, I believe the connections to Bugsnag services hung, which caused our API requests to stack up and eventually reject connections. I've investigated and there is no way to specify a connection or read timeout through bugsnag, however these are available in guzzle and could be easily passed through.

Whether or not there was a networking issue with bugsnag last night or some networking issue on our end or somewhere inbetween, it seems sensible that a timeout on sending the request should be configurable

### Version
v3.16.0 (however I've investigated v3.20.0 and can't see an option for timeout here either

**Comment by xander-jones** [comment]
Hi @henrysearle, as far as I'm aware, all of the Bugsnag services were responding as normal throughout the 4th March (you can see any downtime reports here: https://status.bugsnag.com/), so I would think this was an issue on your side.

We're working on our Guzzle client for PHP, and by extension, Laravel. Discussions around inclusion of a configurable timeout will be taking place. Thank you for your feedback on this.

**Comment by tarsislima** [comment]
Some configurable timeout  will be very useful! Sometimes i have issues  with timeouts on bugsnag notification. But is not possible to change default timeout through bugsnag configuration in this package. I wold like to help implementing this feature.  
are there any guidelines for contributing to this project?

**Comment by yousif-bugsnag** [comment]
Hi @tarsislima, since [v2.21.0](https://github.com/bugsnag/bugsnag-laravel/releases/tag/v2.21.0) it's possible to provide a customized HTTP client via Guzzle which allows you to configure a timeout: https://docs.bugsnag.com/platforms/php/laravel/advanced-client-configuration/

We also now have a default timeout of 15s, so connections will no longer hang forever as was originally reported.
