### ISSUE TITLE
Sub package droped - monolog/monolog

### ISSUE THREAD

**Issue by StoianAlexandru** [bugsnag/bugsnag-laravel#399]
Hello,
I recently installed bugsnag-laravel and after the installation i am getting a message that the "monolog/monolog" package was dropped, just a heads up.

Have a nice day

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. What exactly do you mean, please?

Monolog is still listed as a dependency: https://github.com/bugsnag/bugsnag-laravel/blob/master/composer.json#L19.

**Comment by StoianAlexandru** [comment]
@GrahamCampbell when you install bugsnag, composer notifies me that the monolog package was droped and will not continue to receive suport

**Comment by GrahamCampbell** [comment]
Can you show us what you see? Monolog is definitely not abandoned.

**Comment by StoianAlexandru** [comment]
Sure

"....
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
Writing lock file
Generating optimized autoload files
....
"
this is what i get in the terminal on a fresh composer install.

**Comment by GrahamCampbell** [comment]
That's not monolog. That's moontoast/math, a dependency of Laravel. You will need to upgrade to Laravel 7 to avoid seeing that message. Laravel 6 LTS users can safely ignore it.
