### ISSUE TITLE
Laravel 8.x support

### ISSUE THREAD

**Issue by rihardssceredins** [bugsnag/bugsnag-laravel#410]
### Description

Laravel 8.x is now released, should add support to allow installation on Laravel 8.x projects.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by imjoehaines** [comment]
The next release will support Laravel 8 and should be released today or tomorrow (https://github.com/bugsnag/bugsnag-laravel/pull/409)
