### ISSUE TITLE
API key location

### ISSUE THREAD

**Issue by tillkruss** [bugsnag/bugsnag-laravel#42]
Since L5 `config/services.php` exists. It would be great if the bugsnag API key could be added there and not in it's on file `config/bugsnag.php`.

Maybe even read the `BUGSNAG_API_KEY` using `env()`.

**Comment by jessicard** [comment]
Hey @tillkruss - this change sounds reasonable. If you don't mind making a PR, we can take a look there - if not, we'll try to get around to it soon.

Thanks! :)

**Comment by michelecurletta** [comment]
@tillkruss +1 for API key in config/services.php .
Practise that puts API keys as environment variables is not encouraged by Laravel's gurus.
