### ISSUE TITLE
Call to undefined method Bugsnag\Configuration::getRedactedKeys()

### ISSUE THREAD

**Issue by WebMedic-X** [bugsnag/bugsnag-laravel#435]
### Describe the bug

Not sure why recently stopped receiving Bugsnag reports and then checked the logs and found this error message showing up:

Uncaught Error: Call to undefined method Bugsnag\Configuration::getRedactedKeys() in public_html/vendor/bugsnag/bugsnag/src/Report.php:798

### Environment
* Bugsnag version: v3.26.0 and v2.22.0 of bugsnag-laravel
* PHP version: 7.4.15
* Composer version: 2.0.9
* Laravel version: v6.20.16
* Lumen version (if any):

**Comment by imjoehaines** [comment]
Hey @WebMedic-X 

It looks like your install of bugsnag-php has been corrupted somehow — the Report class is clearly from v3.26.0 as that version introduced the call to `getRedactedKeys`, but the Configuration class can’t be v3.26.0 as it’s missing the `getRedactedKeys` method

Can you let us know how you updated to bugsnag-laravel v2.22.0 and bugsnag-php v3.26.0?

Could you also run the following commands to show the state of your Bugsnag packages:

1. `composer show 'bugsnag/*'`

     This should output :
    ```
     bugsnag/bugsnag            v3.26.0 Official Bugsnag notifier for PHP applications.
    bugsnag/bugsnag-laravel    v2.22.0 Official Bugsnag notifier for Laravel applications.
    bugsnag/bugsnag-psr-logger v1.4.3  Official Bugsnag PHP PSR Logger.
    ```

1. `grep "'version' " vendor/bugsnag/bugsnag/src/Configuration.php`

    This should output:
    ```
            'version' => '3.26.0',
    ```

1. `tail vendor/bugsnag/bugsnag/src/Configuration.php`

    This should output:
    ```
        /**
         * Get the array of metadata keys that should be redacted.
         *
         * @var string[]
         */
        public function getRedactedKeys()
        {
            return $this->redactedKeys;
        }
    }
    ```

If any the above commands show different output, it's likely something has gone wrong when updating bugsnag-php to v3.26.0

Running `composer update 'bugsnag/*'` should fix the issue by ensuring bugsnag-php v3.26.0 is properly installed. If Composer doesn't think there's anything to update, try deleting `vendor/bugsnag` and rerunning that command to force Composer to reinstall the Bugsnag packages from scratch

**Comment by WebMedic-X** [comment]
Hi @xander-jones 

Interestingly, all the commands report exactly what you showed but it was still showing that error

Deleted vendor/bugsnag and re-installed it and I think that solved it

Thank you!

**Comment by xander-jones** [comment]
I have to give props to @imjoehaines for solving this one 👏 , I only added the label 😁 , but thank you for letting us know that this is now resolved!
