### ISSUE TITLE
Prepare for Laravel 9 support

### ISSUE THREAD

**Issue by adevade** [bugsnag/bugsnag-laravel#469]
Laravel 9 is just around the corner, and when I was going to try out the beta it wouldn't install because of this package.

It would be nice if it's supported when Laravel 9 drops (probably) early next month.

**Comment by luke-belton** [comment]
hi @adevade - we're planning to add support for the Laravel 9 release. We'll let you know on this thread when there are any updates.

**Comment by mikkellindblom** [comment]
Any news on this @luke-belton?

**Comment by xander-jones** [comment]
👋  Laravel 9 support is not released yet, but we'll keep you posted when this drops.

**Comment by luke-belton** [comment]
Support for Laravel 9 has [now been added](https://github.com/bugsnag/bugsnag-laravel/pull/477). This was released in [`v2.23.0`](https://github.com/bugsnag/bugsnag-laravel/releases/tag/v2.23.0)  of `bugsnag-laravel` 🎉

**Comment by adevade** [comment]
Nice work! Thank you! 👍
