### ISSUE TITLE
Ignore Exceptions in Laravel

### ISSUE THREAD

**Issue by albertcito** [bugsnag/bugsnag-laravel#474]
### Description

All the unhandled exceptions are send if we [update the logging.php](https://docs.bugsnag.com/platforms/php/laravel/#laravel-5-6) file. But sometimes custom exceptions or others like  `NotFoundHttpException` exceptions are sent, bu I don't want to send those one.

**Describe the solution you'd like**
I would like to be able to set an array of exceptions to don't send the report to Bugsnag.

**Describe alternatives you've considered**
I try to use `app/Exceptions/Handler.php` and removed the config from `logging.php` . But in that case, `Log::error` is not send to Bugsnag.

**Additional context**
I'm using Laravel 8

**Comment by johnkiely1** [comment]
Hi @albertcito. 

You are able to set a list of events to discard using the following configuration option: https://docs.bugsnag.com/platforms/php/laravel/configuration-options/#discard-classes

This is based on classname and sounds like it should fit your use case.

**Comment by albertcito** [comment]
Perfect, looks like it's working properly now. I didn't have that option in my `config/bugsnag.php` file. I guess it's because I installed that version `$ composer require "bugsnag/bugsnag-laravel:^2.0"` that is display in the [documentation](https://docs.bugsnag.com/platforms/php/laravel/#installation).
