### ISSUE TITLE
Fails composer install for Laravel 9

### ISSUE THREAD

**Issue by robertswes** [bugsnag/bugsnag-laravel#479]
### Expected behavior
I am attempting to upgrade Laravel 8 to Laravel 9 I am unable to successfully run composer install

### Observed behavior
Problem 1
    - illuminate/support[v5.6.0, ..., 5.8.x-dev] require php ^7.1.3 -> your php version (8.1.2) does not satisfy that requirement.
    - illuminate/support[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.1.2) does not satisfy that requirement.
    - illuminate/support[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.1.2) does not satisfy that requirement.
    - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.1.2) does not satisfy that requirement.
    - Root composer.json requires bugsnag/bugsnag-laravel ^v2.22.2 -> satisfiable by bugsnag/bugsnag-laravel[v2.22.2].
    - Conclusion: don't install laravel/framework v9.0.0-beta.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.4 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0-beta.5 (conflict analysis result)
    - Conclusion: don't install laravel/framework v9.0.0 (conflict analysis result)
    - Root composer.json requires tightenco/ziggy ^1.4.3 -> satisfiable by tightenco/ziggy[v1.4.3].
    - bugsnag/bugsnag-laravel v2.22.2 requires illuminate/support ^5.0|^6.0|^7.0|^8.0 -> satisfiable by illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev].
    - Only one of these can be installed: illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev], laravel/framework[v9.0.0-beta.1, ..., 9.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
    - tightenco/ziggy v1.4.3 requires laravel/framework >=5.4@dev -> satisfiable by laravel/framework[v9.0.0-beta.1, ..., 9.x-dev].
    - Conclusion: don't install laravel/framework v9.0.0-beta.1 (conflict analysis result)

### Steps to reproduce
follow upgrade guide on Laravel site: https://laravel.com/docs/9.x/upgrade

### Version
^v.2.0 and ^v2.22.2

**Comment by robertswes** [comment]
Apologies, I just now looked and see the recent discussion on the previous issues.
Feel free to close the ticket if my information is redundant.

**Comment by luke-belton** [comment]
Hi @robertswes - we don't support Laravel 9 just yet, however we should be releasing an update for this shortly. As you've noted this is being tracked over at https://github.com/bugsnag/bugsnag-laravel/issues/469, so I'm going to close this issue out.
