### ISSUE TITLE
Updating minor version

### ISSUE THREAD

**Issue by carltondickson** [bugsnag/bugsnag-laravel#482]
### Describe the bug

Trying to update from `v2.22.2` to `v2.23.0`, appear to be locked by bugsnag/bugsnag package.

### Steps to reproduce

Running `composer outdated` shows I have a minor version to pick up

`bugsnag/bugsnag-laravel     v2.22.2 v2.23.0 Official Bugsnag notifier for Laravel applications.`

```
composer prohibits "bugsnag/bugsnag-laravel:v2.23.0"

bugsnag/bugsnag-laravel   v2.23.0  requires          bugsnag/bugsnag (^3.27.0)                   
XXX/xxx-service  0.0.1    does not require  bugsnag/bugsnag (but v3.26.1 is installed)
```

Is this the result of the change here? Should I specify that I also require `bugsnag/bugsnag-php:^3.27.0` at the required version - 

https://github.com/bugsnag/bugsnag-laravel/commit/fb0aba92db7ab8c44dd56415391163f7cc0e1db4

### Environment
* Bugsnag version: bugsnag/bugsnag-laravel:v2.22.2 / bugsnag/bugsnag:v3.26.1
* PHP version: 7.4.22
* Composer version: 1
* Laravel version: 8.66.0

**Comment by johnkiely1** [comment]
Hi @carltondickson ,

Yes the latest version of bugsnag/bugsnag-laravel [requires v3.27.0 of the bugsnag/bugsnag package](https://github.com/bugsnag/bugsnag-laravel/commit/2265825f4b84e7d198fff99dc2df9d0f2465d788). This should be pulled in automatically but if you are specifying bugsnag/bugsnag directly in your own `composer.json` file you would also need to update this to be 3.27.0 to avoid the dependency conflict.
