### ISSUE TITLE
Unable to create configured logger

### ISSUE THREAD

**Issue by solarsilk** [bugsnag/bugsnag-laravel#484]
### Describe the bug
For all unhandled errors, I see the below error message in my `laravel.log` file.

When setting `LOG_CHANNEL=stack` (['daily','bugsnag']), the error **is not** reported to the BS dashboard. If I set `LOG_CHANNEL=bugsnag` I still see that error above, but the error **is** reported to the BS dashboard.

Manual reporting like `Bugsnag::notifyError('TestError', 'Testing bugsnag errors',...` works as expected.

### Steps to reproduce
1. I have a normal installation
2. Nothing I can see that's different from my other BS installs that are working fine
3. I've done `php artisan config:clear` etc doesn't seem to help

### Environment
* Bugsnag version: 2.23.0
* PHP version: 8.1.4
* Composer version: 2.2.6
* Laravel version: 9.5.1
* Lumen version (if any): n/a

Error messages:

```
[2022-03-24 11:53:39] laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /Users/xxxx/xxx/xxx/xxx/xxxx/vendor/bugsnag/bugsnag-laravel/src/BugsnagServiceProvider.php:193)
```
[BugsnagServiceProvider line 193](https://github.com/bugsnag/bugsnag-laravel/blob/49ba46b2e010401a4ac8cff4a2117b4479525664/src/BugsnagServiceProvider.php#L193)

**Comment by solarsilk** [comment]
I believe it's fixed. I tried removing bugsnag and noticed an error: `Fatal error: Uncaught ReflectionException: Class "config" does not exist in xxx/src/Illuminate/Container/Container.php:877`. Looked into that and ended up doing `php artisan config:cache` which writes the `bootstrap/cache/config.php` file. The error went away.

Seems like bugsnag needs that cached config in order to work properly. I never had that issue before. Maybe it's a change in the package??

**Comment by xander-jones** [comment]
Hey @solarsilk, glad to hear the issue is resolved! For additional config of Bugsnag other than just setting the API key, I would have expected `php artisan vendor:publish` to have been run in any case prior to configuration being made during the [install](https://docs.bugsnag.com/platforms/php/laravel/#basic-configuration). The published config file should then be edited.

**Comment by solarsilk** [comment]
Thanks @xander-jones . The installation instructions say "If you’d like to configure Bugsnag further, create and edit" which implies it's optional. Are you saying that publishing the config for this package is a requirement? From my experience above, it seems like it is.

**Comment by xander-jones** [comment]
Hey @solarsilk, sorry I wasn't clear whether you were using environment variables to set your Bugsnag configuration, or using the `config/bugsnag.php` config file. You don't _need_ to use the config file. But, if you're using environment variables and have previously cached your environment variables, you'll need to keep updating the cache every time you make changes to the `.env` file.

[Laravel don't suggest](https://laravel.com/docs/9.x/configuration#configuration-caching) that you cache environment variables in a local dev environment, so might be worth running `php artisan cache:clear` if you want to continue using environment variables without needing to run `php artisan config:cache` each time something changes, or switch to using the configuration file method instead.

**Comment by solarsilk** [comment]
thanks @xander-jones I cleared everything and published the `config/bugsnag.php` and I think everything is good now. Thanks.
