### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by adamwathan** [bugsnag/bugsnag-laravel#50]
Would be awesome to tag a new version for this change so we can configure the package a bit more "idiomatic Laravel 5" style: https://github.com/bugsnag/bugsnag-laravel/commit/a647ec923d2b55d0ea2715d4e5e087d9c07afca5

Thanks folks! :blush:

**Comment by jessicard** [comment]
Hey @adamwathan! I want to go ahead and tag a new version ASAP, but was wondering if you could weigh in on https://github.com/bugsnag/bugsnag-laravel/pull/49#issuecomment-104072407 first, in case that causes any issues

**Comment by adamwathan** [comment]
Hey @jessicard, what's there will be fine, no issues. I don't think Graham noticed the code was in the exception handler rather than a service provider, unless he was suggesting to bind the exception handler in the service provider, which is a bit more code but would mean you could eliminate the `app()` call completely by just injecting the Bugsnag Client directly.

For what this does though, I don't know that it's worth it, at least not to block the release. The `app()` call works exactly as the `global $app` call did, so everything will work just as well as before :+1: Could be revisited down the road if it's decided that injecting the dependency is a really big win over the service location for any future extensibility reasons or anything, but functionally it's all the same as before.

**Comment by ConradIrwin** [comment]
Thanks! Released v1.5.0 :).
