### ISSUE TITLE
Bugsnag Shows js stack trace and php error codes but no php stacktrace.

### ISSUE THREAD

**Issue by ndethi** [bugsnag/bugsnag-laravel#512]
### Expected behavior
*Bugsnag should show the php stack trace for error 500.*

### Observed behavior
* Error · Request failed with status code 500
webpack-internal:///85061:16:15 createError
webpack-internal:///36026:17:12 settle
webpack-internal:///55448:66:7 XMLHttpRequest.onloadend*

Reports error code only and shows vue.js stack trace

Here are the bugsnag and logging configs:

#### config/logging.php
```
'default' => env('LOG_CHANNEL', 'stack')
...
'channels' => [
    'stack' => [
      'driver' => 'stack',
      'channels' => ['single', 'bugsnag'],
      'ignore_exceptions' => false,
    ],
    'single' => [
      'driver' => 'single',
      'path' => storage_path('logs/laravel.log'),
      'level' => env('LOG_LEVEL', 'debug'),
    ],

...
    'bugsnag' => [
      'driver' => 'bugsnag',
    ],

```

#### config/app.php

```
       /*
         * Package Service Providers...
         */
        Intervention\Image\ImageServiceProvider::class,
        Bugsnag\BugsnagLaravel\BugsnagServiceProvider::class,

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,

        App\Providers\BugsnagServiceProvider::class,
    ],



```

#### config/bugsnag.php

```
'release_stage' => env('BUGSNAG_RELEASE_STAGE'),
'notify_release_stages' => empty(env('BUGSNAG_NOTIFY_RELEASE_STAGES')) ? null : explode(',', str_replace(' ', '', env('BUGSNAG_NOTIFY_RELEASE_STAGES'))),

```
#### .env

```
APP_ENV=production
APP_DEBUG=false
APP_LOG_LEVEL=debug
...
BUGSNAG_API_KEY= key
BUGSNAG_QUERY_BINDINGS=true

```

**Comment by hannah-smartbear** [comment]
Hi @ndethi,

Please could you tell us a bit more about your project setup? When you say PHP stacktrace, what exactly are you expecting to see?

Please could you send a link to the error in question along with answers to the questions above at support@bugsnag.com to help us investigate this further?

**Comment by johnkiely1** [comment]
Going to close this out as we have not heard from you in a while. We do need some additional information in order to investigate this further. Happy to reopen as necessary.
