### ISSUE TITLE
laravel 10 compatibility

### ISSUE THREAD

**Issue by Zae** [bugsnag/bugsnag-laravel#519]
Hi,

Is it possible to tag a new release with laravel 10 compatibility?

**Comment by ajsheldon93** [comment]
https://github.com/bugsnag/bugsnag-laravel/issues/520

https://github.com/bugsnag/bugsnag-laravel/pull/518

**Comment by imjoehaines** [comment]
Released in [v2.26.0](https://github.com/bugsnag/bugsnag-laravel/releases/tag/v2.26.0)
