### ISSUE TITLE
How to set app version automatically?

### ISSUE THREAD

**Issue by mvynhb** [bugsnag/bugsnag-laravel#530]
This is more of a question than a bug, but how are you setting the app version for new released?

```php
Bugsnag::setAppVersion('1.2.3');
```

Are you manually changing the version every time you release? Isn't there a way to do this automatically?

**Comment by johnkiely1** [comment]
Hi @mvynhb, 
You can also set the BUGSNAG_APP_VERSION environment variable, or set this within config/bugsnag.php:
https://docs.bugsnag.com/platforms/php/laravel/configuration-options/#app-version

It's worth mentioning you do not have to set this but the idea is that it would follow along with whatever versioning scheme you are using.    

How do you determine a version number for your next release? Are you setting this somewhere else within your app?

**Comment by mvynhb** [comment]
hi @johnkiely1 
Currently I don't maintain any version number for my releases. I do not want to have to update this version number manually every time, cause I could forget to do so.

Could I do something like below when deploying to use the timestamp as an automatic version? I am not sure if below works. Is it common to always manually update your app version in the source code before releasing? Just wondering what others are doing.

```php artisan bugsnag:deploy --version date +%s```

**Comment by johnkiely1** [comment]
You don't need to set this at all, and it's off by default. Your events will still appear on the dashboard, just without a app version. Setting an app version could be useful to help debugging errors. For example if all events of an error are reported with v2.0 and was never seen for v1.0 you may have introduced a bug in v2.0 so narrows down the places in the code to look. 

I can't say with any authority what others are doing within the industry but I imagine it varies and is mainly down to personal preference and company procedures and workflows.

**Comment by mvynhb** [comment]
I understand the app version is not required, but if not set I can't really use options like `Mark as fixed`, since that uses the version to determine if error happens again in new release. 

I will think of some solution, most likely using the timestamp. Thanks for the support though :+1:
