### ISSUE TITLE
Exceptions in failed Jobs running in queue worker aren't reported to bugsnag.

### ISSUE THREAD

**Issue by bernardwiesner** [bugsnag/bugsnag-laravel#535]
### Describe the bug
If there is an exception in a Job running through the laravel queue worker, and the job fails after the max tried attempts due to the exception, the exception is not reported to bugsnag. This is due to the queue worker being a long lived process that catches exceptions if they occur.

The only way to report these errors is to define in every Job a `failed` [method](https://laravel.com/docs/11.x/queues#cleaning-up-after-failed-jobs) and report the exception there.

However this is tedious to do for every Job. There should at least be an option in bugsnag to report failed job exceptions.

FYI: I also have to set `Bugsnag::setBatchSending(false)` in AppServiceProvider so the exception can be reported since queue worker does not exit on its own.

### Steps to reproduce
- Have a running queue worker (`php artisan queue:work`)
- Create a Job that throws an Exception.
- Exception is not reported to bugsnag

### Environment
* Bugsnag version: 2.26
* PHP version: 8.1
* Composer version: 2.6
* Laravel version: 10.10

**Comment by mclack** [comment]
Hi @bernardwiesner 

Apologies for the delay in response.

We would expect these exceptions to be reported without needing to define a `failed` method in each job. We'd be interested to see your BugSnag configuration code, as well as whether you have any discard rules set up on your BugSnag dashboard, or if you are discarding any events from your app within an [on-error callback](https://docs.bugsnag.com/platforms/php/laravel/customizing-error-reports/#adding-callbacks).

As this is a public thread, please feel free to share any additional details with us directly by contacting support@bugsnag.com.

**Comment by bernardwiesner** [comment]
Hi @mclack 

Thanks for the reply. 

I do not have any discard rules set. Could you refer me to the block of code in this repo that has the logic to deal a failure inside a Job to be reported to bugsnag? 

As you know laravel is catching exceptions inside the queue worker and just calling the failed method, and emitting some events, but I don't think you are listening to any of those events. 

If you could refer me to those code where the logic for dealing with failed jobs in the queue worker is implemented that would be very helpful, thanks!

**Comment by clr182** [comment]
Hi @bernardwiesner 

Thank you for confirming. 

You can find more information on the handling of unhandled errors in this repo [here](https://github.com/bugsnag/bugsnag-laravel/blob/b1d31a4ed2433cf7a067a13fe0d68d0f6d9d3558/src/Middleware/UnhandledState.php). 

We believe instances of the errors you have highlighted should be captured and we do have test fixtures in place to test against such a case ([here](https://github.com/bugsnag/bugsnag-laravel/blob/b1d31a4ed2433cf7a067a13fe0d68d0f6d9d3558/features/queues.feature#L9) & [here](https://github.com/bugsnag/bugsnag-laravel/blob/b1d31a4ed2433cf7a067a13fe0d68d0f6d9d3558/features/fixtures/laravel10/app/Jobs/UnhandledJob.php)). However, for further investigation would it be possible for you to reproduce this issue and try sending these errors to an external webhook? Sharing the payload with us via zendesk if it is received. Alternatively, if you could also share any error logging received based off of this unhandled crash inside a job. 

As this is a public forum, please feel free to reach out to us at support@bugsnag.com to share this additional information.

**Comment by clr182** [comment]
Hi @bernardwiesner 

As this thread has not seen any activity for some time I am going to close this issue out. 
If you would like to continue this investigation please reach out and we can reopen this issue.

**Comment by bernardwiesner** [comment]
Hi @clr182 

Thanks, I checked and noticed that failed jobs were actually getting reported [here](https://github.com/laravel/framework/blob/d978117ce5c246c8f971853df3f958b7dc17f016/src/Illuminate/Queue/Worker.php#L391). That is only when `Bugsnag::setBatchSending(false)` is set, if its not set, the errors don't get reported since the queue worker is long running. I think that was my original confusion. Of course the logging.php also has to have `bugsnag` set as a channel in your default log channel.

**Comment by mclack** [comment]
Hi @bernardwiesner 

Thanks for following up.

It sounds like this is now resolved for you. If you do continue to have any issues or questions, then please feel free to reach out again. If you'd like, you can open a support ticket with us directly by contacting support@bugsnag.com.
