### ISSUE TITLE
There is a unresolved usage in LaravelLogger file giving error when using with ide-helper package

### ISSUE THREAD

**Issue by mertaydin** [bugsnag/bugsnag-laravel#541]
### Describe the bug
When you use laravel-bugsnag package with barryvdh/laravel-ide-helper, if you run 

```
php artisan ide-helper:meta 
```

command giving this error.

<details><summary>Error messages:</summary>

```
 laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (ReflectionException(code: 0): Class 'Illuminate\\Contracts\\Logging\\Log' not found.
```
</details>

Because of in 
```
Bugsnag\BugsnagLaravel\LaravelLogger.php 
```
file's

```
  Illuminate\Contracts\Logging\Log 
``` 
namespace definition

### Steps to reproduce
1. Go to terminal
2. run php artisan ide-helper:meta command
3. open storage/logs/laravel.log (You can open whichever log file is in your project)

### Environment
* Bugsnag version: 2.28
* PHP version: 8.3
* Composer version: 2.2.21
* Laravel version: 11.28.1

**Comment by clr182** [comment]
Hi @mertaydin 

Can you please confirm that you have followed the documentation for configuring the logger and ensured correct binding to `Psr\Log\LoggerInterface` ? This will eliminate the reliance on the deprecated `Illuminate\Contracts\Logging\Log interface`, which I believe is what was causing the issue.

For convenience you can find those docs here: https://docs.bugsnag.com/platforms/php/laravel/#laravel-5-6

**Comment by mertaydin** [comment]
Yes, I did everything according to documentation. I don't have any problem with bugsnag. But I think problem is unresolved namespace which was found by ide-helper package. It's scanning all classes for ide helper for autocompletion.

**Comment by hannah-smartbear** [comment]
Hi @mertaydin,
 
To help us investigate this further, are you able to provide your full BugSnag configuration, along with your full `composer.json` file? Or even better, would you be able to provide a stripped down example app that reproduces this?

If you are concerned about sharing these files publicly then please feel free to reach out to us via [support@bugsnag.com](mailto:support@bugsnag.com).

**Comment by mertaydin** [comment]
I sent details with email to support@bugsnag.com

**Comment by mclack** [comment]
Hi @mertaydin 

As you have now opened a support ticket with us directly, we are going to close this issue and continue the conversation over there. If you have any questions, please respond to us on the ticket.
