### ISSUE TITLE
LaravelLogger references class that no longer exists (Illuminate\Contracts\Logging\Log) in Laravel 5.6+

### ISSUE THREAD

**Issue by justincdotme** [bugsnag/bugsnag-laravel#546]
### Expected behavior
`composer update` doesn't produce the error `laravel.EMERGENCY: Unable to create configured logger. Using emergency logger. {"exception":"[object] (ReflectionException(code: 0): Class 'Illuminate\\Contracts\\Logging\\Log' not found`

### Observed behavior
The class `Bugsnag\BugsnagLaravel\LaravelLogger` imports this class on line 8 https://github.com/bugsnag/bugsnag-laravel/blob/master/src/LaravelLogger.php#L8 and causes an error to be written to the log if `composer update` is run while the `.env` includes a reference to the `bugsnag` log channel in the `LOG_STACK` or if it's referenced in any of the log channels in that file in Laravel 5.6+

### Steps to reproduce
1. Follow the installation steps listed on this page in a Laravel 5.6 application. In this case I am using Laravel 11.  https://docs.bugsnag.com/platforms/php/laravel/
2. Add a logging channel for `bugsnag` to `config/logging.php`
3. Reference that channel in `.env`
4. Run `composer update`
5. Observe the error in the log file. In my case it was in `storage/logs/laravel.log`.

### Version
2.28.0

### Additional information
The Laravel team removed the `Illuminate\Contracts\Logging\Log` class in Laravel 5.6 because it was a duplicate of `Psr\Log\LoggerInterface`. This was mentioned in the Laravel 5.6 upgrade guide: https://laravel.com/docs/5.6/upgrade

I'm not sure that the reference to the `Psr\Log\LoggerInterface` is even needed in `Bugsnag\BugsnagLaravel\LaravelLogger` since that class ultimately extends `Psr\Log\AbstractLogger` which already implements the correct interface. 

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by GrahamCampbell** [comment]
This is a non-issue. That class only exists to support older Laravel versions. On newer Laravel versions, the entire class is not used at all.

**Comment by GrahamCampbell** [comment]
See https://github.com/bugsnag/bugsnag-laravel/blob/master/src/BugsnagServiceProvider.php#L346.

**Comment by justincdotme** [comment]
@GrahamCampbell I guess I'm not following why it's not an issue. `Log::class` on line 346 of that service provider is `Illuminate\Contracts\Logging\Log` but the installation instructions state to add that service provider to the `$providers` array in `bootstrap/providers.php`.

**Comment by GrahamCampbell** [comment]
That line checks to see if the class exists, so that we can do the correct thing on both older and newer Laravel.

**Comment by justincdotme** [comment]
I see, is there a clean way to prevent that error from appearing in the `laravel.log` then?

**Comment by GrahamCampbell** [comment]
Are you using the latest version of this package, or a version before that interface_exists check was added?
