### ISSUE TITLE
Class 'App\Http\Controllers\Bugsnag' not found

### ISSUE THREAD

**Issue by raja** [bugsnag/bugsnag-laravel#58]
When I attempt to use Bugsnag::notifyException or Bugsnag::notifyError, I get the following error (captured in bugsnag itself)

Symfony\Component\Debug\Exception\FatalErrorException
Class 'App\Http\Controllers\Bugsnag' not found

This in a Laravel 5.0.x app

**Comment by frankiecmk** [comment]
# Add the `BugsnagFacade` to the `aliases` array
'aliases' => array(
    ...
    'Bugsnag' => 'Bugsnag\BugsnagLaravel\BugsnagFacade',
)

**Comment by loopj** [comment]
@raja looks like @frankiecmk already answered this one, you'll need to make sure you add the BugsnagFacade to the aliases array!

**Comment by vicker** [comment]
@frankiecmk @loopj How about Lumen?

**Comment by sonicfive** [comment]
Simple. Place a backslash before you call it:
`\Bugsnag::notifyException(new \Exception("My amazing exception"));`
