### ISSUE TITLE
Lumen - Class 'Bugsnag\\BugsnagLaravel\\ServiceProvider' not found

### ISSUE THREAD

**Issue by matiux** [bugsnag/bugsnag-laravel#60]
There is a problem with Lumen Service Provicer.
in BugsnagLumenServiceProvider.php missing inclusion of Illuminate\Support\ServiceProvider so when runs, gives this error

Class 'Bugsnag\\BugsnagLaravel\\ServiceProvider' not found in /.../vendor/bugsnag/bugsnag-laravel/src/Bugsnag/BugsnagLaravel/BugsnagLumenServiceProvider.php on line 4

Temporarily I have solved adding

use Illuminate\Support\ServiceProvider;

**Comment by andreascreten** [comment]
I also have this issue, any updates on this?

**Comment by jessicard** [comment]
Hey @matiux and @andreascreten - I just merged https://github.com/bugsnag/bugsnag-laravel/pull/56 which should solve this issue. Thanks @cfralick!
