### ISSUE TITLE
Configurable user fields

### ISSUE THREAD

**Issue by fredrkr** [bugsnag/bugsnag-laravel#64]
Since you're already adding the id from the logged in user in both the Laravel and Lumen service providers, I propose that you let us configure which user-fields to include in the Bugsnag-report. This way, we avoid having to use global functions or calling setUser() ourselves to add user data.

I already forked the repo and commited a few changes to make this happen and it seemed to work fine. Haven't issued a PR yet, because I wanted to ask you what you think first.

Thanks!

**Comment by dennisoderwald** [comment]
+1

**Comment by GrahamCampbell** [comment]
Thanks. We're starting work on a new major version of this package soon. We'll take all the feedback into account.

**Comment by GrahamCampbell** [comment]
I'm about to add a setUser function to the error class on the current version so that should be available to everyone very soon.

**Comment by GrahamCampbell** [comment]
Keeping this open though since we're not done yet.

**Comment by GrahamCampbell** [comment]
Keeping this open though since we're not done yet.

**Comment by GrahamCampbell** [comment]
Done in 2.x of this package. You can set `user` to false in our config, and that will cancel the registration of our `AddUserMiddleware`.

**Comment by GrahamCampbell** [comment]
I'll be writing full docs before we release.
