### ISSUE TITLE
Bugsnag requires an API key even if it's not supposed to report

### ISSUE THREAD

**Issue by phaza** [bugsnag/bugsnag-laravel#65]
Even if you've set bugsnag to only report exceptions in production, it still requires an api key in other modes. Worst of all, it gets trapped in an endless exception loop where it throws an exception for no api key being present, and then catches it and tries to submit it. *repeat*.

I solved it by having my config look like this:
`'api_key' => env('BUGSNAG_API_KEY', ''),`
compared to:
`'api_key' => env('BUGSNAG_API_KEY'),`

**Comment by ecommerceappbook** [comment]
echo this issue. Thanks @phaza for pointing out this solution. I think either the doc needs to be updated or this "no api key" issue needs to be addressed.

**Comment by GrahamCampbell** [comment]
Right, this is because we're booting everything in order to decide if we need to log or not. We're looking into doing some refactoring to address this. I'll get back to you soon.

**Comment by GrahamCampbell** [comment]
> I solved it by having my config look like this:

Yes, that looks just fine. :)

**Comment by GrahamCampbell** [comment]
This will be fixed in the next release/
