### ISSUE TITLE
Add configuration option to disable autonotification

### ISSUE THREAD

**Issue by loopj** [bugsnag/bugsnag-laravel#66]
We should add a configuration option to disable adding of the laravel `error` hooks, in the case people want to add these hooks themselves:
https://github.com/bugsnag/bugsnag-laravel/blob/master/src/Bugsnag/BugsnagLaravel/BugsnagLaravelServiceProvider.php#L29

Thinking of using `autoNotify` in the bugsnag config.

**Comment by GrahamCampbell** [comment]
This will happen as part of https://github.com/bugsnag/bugsnag-php/issues/205. We can 100% allow laravel's exception handler to just do it's thing here.

**Comment by GrahamCampbell** [comment]
@loopj See https://github.com/bugsnag/bugsnag-php/pull/213. Basically, if you're using laravel, you don't setup our handler. Otherwise, you might want to. The autoNotify config is no longer needed.
