### ISSUE TITLE
Undefined index: HTTP_HOST

### ISSUE THREAD

**Issue by fabbrikk** [bugsnag/bugsnag-laravel#68]
When, for some reasons ,the variable $_SERVER['HTTP_HOST'] is null, this file generate an error
**Uncaught exception 'ErrorException' with message 'Undefined index: HTTP_HOST'** in 
**vendor/bugsnag/bugsnag/src/Bugsnag/Request.php** on row 74,
```php
return $schema.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
```
I changed it to:
```php
$host = array_key_exists( 'HTTP_HOST', $_SERVER) ? $_SERVER['HTTP_HOST'] : gethostbyaddr($_SERVER["REMOTE_ADDR"]);
return $schema.$host.$_SERVER['REQUEST_URI'];
```
It's correct or I'm missing something? Why this can happen?

**Comment by GrahamCampbell** [comment]
Under what conditions does this happen please? Are you running a console app?

**Comment by GrahamCampbell** [comment]
Could you `var_dump($_SERVER)` for me please?

**Comment by fabbrikk** [comment]
Sorry but I changed from BugSnag to Sentry. I'll try again BugSnag later this year.

**Comment by mverma16** [comment]
@GrahamCampbell 
please help we are getting these erros.
![1](https://cloud.githubusercontent.com/assets/10759797/16722805/b68d3348-4766-11e6-8f38-34e71cd36e9c.PNG)

![2](https://cloud.githubusercontent.com/assets/10759797/16722857/214e6512-4767-11e6-83c6-d96d99004c58.PNG)

Stack-trace shows bugsnag package's files, can you help to solve it, Please reply here or I have to open a new issue.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. A handshake timeout is something we can't do anything about. It means your server failed to complete the SSL negotiation in time. You could turn off SSL if you're having problems with this. If your bugsnag config file, set the endpoint to `Bugsnag_Configuration::$DEFAULT_NON_SSL_ENDPOINT`.

The fact that this error is crashing your application is not desirable though. We should be logging the failed request, and continuing. I'll create a new issue regarding this.
