### ISSUE TITLE
Where to add username exception

### ISSUE THREAD

**Issue by og6k** [bugsnag/bugsnag-laravel#74]
In the tutorial on laracast, Jeffrey Way put it in the global.php file. I do not have that file in laravel 5.1. How do I implement the extra config? Do I have to create the global.php file?

**Comment by GrahamCampbell** [comment]
What Laravel version are you using please?

**Comment by GrahamCampbell** [comment]
In Laravel 5.1, you can do this in the boot function of your app service provider.
