### ISSUE TITLE
Remove example code that has a class named "User" in the namespace "App" from distribution archive

### ISSUE THREAD

**Issue by atrauzzi** [bugsnag/bugsnag-laravel#75]
Just added your library to my project and my IDE is quite upset that there are multiple definitions for `App\User`.  It's fairly eager to scan all project directories and as a result, thinks that in some way your sample code could end up being executed.

**Comment by kattrali** [comment]
Having an example with a class named "User" in an "App" seems like a fairly common case for our users, so it doesn't make sense to remove the example. Perhaps there is an editor setting to prevent this edge case?

**Comment by atrauzzi** [comment]
@kattrali Your examples are entire laravel projects.  You shouldn't be doing this.

Move them to another repository, or at the very least change the namespaces used for the example projects to be something like `Example\App\User`, etc...

Editor settings would have to be set manually, once for each package that was careless enough to make this mistake.  You think it's acceptable to make everyone have to do that for packages, or just yours because it's special in some way?

**Comment by kattrali** [comment]
> Your examples are entire laravel projects.

Indeed. The intent is that they are runnable and can test that the integration is working properly, not that they are included in production code, in an `Example` namespace or otherwise.

**Comment by atrauzzi** [comment]
Doesn't matter, most IDEs will pick up on the code.  You are making a bad assumption that what you have done is normal.

**Comment by philbates35** [comment]
Have to agree with @atrauzzi on this one. You could add the `examples` directory to `.gitattributes` too exclude it from there package version of the repo? That way the examples would exist in the GitHub repo for reference, but not in the application's `vendor` directory.

**Comment by atrauzzi** [comment]
Yeah, so long as it results in the files not showing up, then it would be an acceptable solution.

All the static analyzers I've seen don't work by reading the composer manifests, they work by manually crawling the entire project directory and building their own "view of the world".
Putting entire Laravel projects inside of a package is guaranteed to create headaches and there is a reason why *nobody does it*.

**Comment by kattrali** [comment]
> You could add the examples directory to `.gitattributes` too exclude it from there package version of the repo?

That's a good idea actually. I'd like the examples to be readily available in the repository but am open to it not being in the packaged distribution.

**Comment by kattrali** [comment]
I checked the packaged archives and while the laravel library was packaged with exclusions properly, the base PHP library didn't have them, which was fixed by https://github.com/bugsnag/bugsnag-php/commit/aa2cad9e32a7e5ce35b3699c3637079646a1c2e7 . Thanks!

**Comment by atrauzzi** [comment]
@kattrali - Much better!  I don't know if it's apparent, but I was dismayed that this ticket was closed without proper consideration.  Moreso that it took another person to "drive the point home" before you were willing to reconsider.
If something you intended to be helpful ends up sabotaging tooling like phpstorm (probably THE most popular PHP IDE), it stands to reason something is wrong.  From your tone during triage, it might be important to carefully consider what people suggest before dismissing a concern out of hand.

Happens to the best of us, but worth remembering. :)

**Comment by jimmypuckett** [comment]
This is back with v2.15.0 Release
