### ISSUE TITLE
Update installation instructions to only publish bugsnag assets

### ISSUE THREAD

**Issue by snmaynard** [bugsnag/bugsnag-laravel#76]
"php artisan vendor:publish" publishes for all packages not only bugsnag, since this command has unwanted sideffects when using other packages it should be changed to only publish bugnsag info.

There are to options that might help
--provider[=PROVIDER] The service provider that has assets you want to publish.
--tag[=TAG] One or many tags that have assets you want to publish. (multiple values allowed)

**Comment by kattrali** [comment]
Fixed by #79!

**Comment by marcorivm** [comment]
This needs to be updated here too:
https://bugsnag.com/accounts/scitus/projects/laravel-6/integrate
