### ISSUE TITLE
Do not boot client if not in an environment that requires bugsnag

### ISSUE THREAD

**Issue by atrauzzi** [bugsnag/bugsnag-laravel#77]
If I'm in an environment that won't be making use of bugsnag, the library shouldn't require that a key even be provided.  It should just fall through back to normal Laravel error reporting without attempting to instantiate the client.

**Comment by koorb** [comment]
I agree, my continuous integration tests are failing because I'm not specifying an API key

**Comment by kattrali** [comment]
Thanks for the report @atrauzzi. This makes a lot of sense, and should be fixed soon in #86. Closing this however as a duplicate of #65.

**Comment by atrauzzi** [comment]
:+1: :D

**Comment by shineability** [comment]
Hello!

 

New message, please read <http://autoinsurance365.xyz/talk.php?4i>

 

Maarten@troonbeeckx.net

**Comment by shineability** [comment]
Hello!

 

New message, please read <http://brentallsupvacationspots.com/several.php?uem>

 

Maarten@troonbeeckx.net
