### ISSUE TITLE
Not functioning

### ISSUE THREAD

**Issue by aewing** [bugsnag/bugsnag-laravel#80]
I've included this package and have published the mentioned configs and set up my API key in .env; I have extended my Exception Handler as instructed. I am not getting any exceptions in my BugSnag control panel, even when calling Bugsnag::notifyError('ErrorType', 'Test Error'); from tinker.

**Comment by kattrali** [comment]
Hi @aewing, can you provide some additional information:

- What version of Laravel are you using?
- What version of PHP are you using?

**Comment by snmaynard** [comment]
Closing as we haven't heard back.
