### ISSUE TITLE
More configs

### ISSUE THREAD

**Issue by scottconnerly** [bugsnag/bugsnag-laravel#81]
Currently, the config file only allows 5 things to be configured. However, in https://github.com/bugsnag/bugsnag-php/blob/master/src/Bugsnag/Configuration.php there are many more configurations available. I'm most interested in being able to set Bugsnag_Configuration::hostname, but could definitely see using other ones from there too.

**Comment by kattrali** [comment]
Hi @scottconnerly! I just shipped version 1.6.2, which adds the ability to set the existing configuration options via [environment variables](https://github.com/bugsnag/bugsnag-laravel#environment-variables), as well as [adding documentation for how to leverage the options in the PHP notifier directly](https://github.com/bugsnag/bugsnag-laravel#configuration-options). Hopefully this helps.

**Comment by scottconnerly** [comment]
How would I set the value in bugsnag/bugsnag-php for Bugsnag_Configuration::hostname? It still seems to be locked away. Could you add a mechanism that allows me to set any bugsnag-php config by way of the bugsnag-laravel config?

**Comment by scottconnerly** [comment]
PR #82 would take care of this issue. Would you please consider accepting it? Thanks -SC

**Comment by kattrali** [comment]
Ah, I think I misunderstood. The current behavior allows for setting additional configuration options via the global `$bugsnag` object ([which is available on on `app`](https://github.com/bugsnag/bugsnag-laravel/blob/master/src/Bugsnag/BugsnagLaravel/BugsnagLaravelServiceProvider.php#L55)), so you should be able to use `$bugsnag->setHostname` and get the desired effect.
