### ISSUE TITLE
Bugsnag Laravel 5.1 Issue

### ISSUE THREAD

**Issue by ZacheryPD** [bugsnag/bugsnag-laravel#83]
I am seeing what I think is a similar problem to #78.  I am using php version 5.6.10 and laravel 5.1. 

My Exception/handler.php:
<pre>
//use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Bugsnag\BugsnagLaravel\BugsnagExceptionHandler as ExceptionHandler;
</pre>

I've only made one change to my config/Bugsnag.php
<pre>
	'notify_release_stages' => null, //['production', 'staging', 'local'],
</pre>

so it will report in my dev environment (for testing.)

I've also set my BUGSNAG_API_KEY in my .env and if I remove it from my .env, my app issues an error, which I think is a good sign.  

Unfortunately, nothing appears in my busgnag dashboard at all.  I'm starting to wonder if it's possible that my user's API key doesn't have sufficient permission or something like that.  Has anyone seen a similar problem?  My configuration is basically out of the box with the exception of turning off notify release stages as they do in the example app.

**Comment by bkuhl** [comment]
Your config file path should be `config/bugsnag.php`, not `Bugsnag.php`

**Comment by MichaelObi** [comment]
I have this exact issue and it has nothing to do with the config file name from what i can tell.
Running `Bugsnag::notifyError("ErrorType", "Something bad happened here too");` sends an error successfully to my dashboard. It's really frustrating me.

**Comment by chicag0** [comment]
I'm also having this issue (No errors in BugSnag unless I send them from Tinker).  Running Laravel 5.0 rather than 5.1

**Comment by GrahamCampbell** [comment]
Are there any errors in your php level log file please?

**Comment by MichaelObi** [comment]
Was the bug fixed? I dropped bugsnag for a while but will love to get back on it

**Comment by GrahamCampbell** [comment]
I'm not able to replicate this issue. Perhaps you need to run `php artisan config:cache`?
