### ISSUE TITLE
Feature: Whitelist exceptions

### ISSUE THREAD

**Issue by viezel** [bugsnag/bugsnag-laravel#87]
Would be very nice to be able to put an array of whilelisted exceptions in the config. Often you use Exceptions in API responses, like validation etc. But such an exception should not go to Bugsnag, since its thrown by design.

Can you add this?

**Comment by CristianGiordano** [comment]
You can use the `$dontReport` attribute.

**Comment by GrahamCampbell** [comment]
Yeh, this feature already exists.

**Comment by snmaynard** [comment]
Yeah you can return false from a beforeNotify function as mentioned [here](https://github.com/bugsnag/bugsnag-php#setbeforenotifyfunction)

**Comment by stueynet** [comment]
@CristianGiordano can you provide any more detail on that? Put the $dontReport attribute where? Similar with the beforeNotify function. Where is that supposed to go? I don't reference Bugsnag anywhere in my application. It just works out of the box with a bit of config. So where in our application are we meant to put this stuff? Would be great if the documentation had one or two more sentences.
