### ISSUE TITLE
Argument 1 passed to Bugsnag_Error::setPHPException() must be an instance of Exception, instance of ParseError given

### ISSUE THREAD

**Issue by canfiax** [bugsnag/bugsnag-laravel#89]
I am running php 7.0 on a homestead server, but I am getting following error:

    Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_RECOVERABLE_ERROR) Type error: Argument 1 passed to Bugsnag_Error::setPHPException() must be an instance of Exception, instance of ParseError given, called in /home/vagrant/Projects/project/vendor/bugsnag/bugsnag/src/Bugsnag/Error.php on line 36

What is wrong?

**Comment by o5** [comment]
I have same error. I think, [this commit](https://github.com/bugsnag/bugsnag-php/commit/679ff2f4972b01c6f6b833d4c50dd379e0f32e89) does not cover all cases.

**Comment by kattrali** [comment]
Hi @canfiax, I just released an update to bugsnag-php (v2.6.1), which includes a fix for this issue. You should be able to `composer update` to resolve this.
