### ISSUE TITLE
Requires publishing configuration

### ISSUE THREAD

**Issue by bkuhl** [bugsnag/bugsnag-laravel#92]
Currently this package requires that configuration be published.  This is an annoying step and it would be ideal if we didn't have to publish the config and the package would read the environment variables out of the box.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Sounds good to me. Are you able to send a PR please?

**Comment by bkuhl** [comment]
Looks like someone implemented that since this issue was created.

**Comment by GrahamCampbell** [comment]
Doesn't looks like it? https://github.com/bugsnag/bugsnag-laravel/blob/master/src/config/config.php

**Comment by bkuhl** [comment]
Ah... I looked at https://github.com/bugsnag/bugsnag-laravel#environment-variables.  I'll submit a PR

**Comment by GrahamCampbell** [comment]
Thank you. :pizza:
