### ISSUE TITLE
Laravel 4.x version of the package

### ISSUE THREAD

**Issue by pafelin** [bugsnag/bugsnag-laravel#94]
Hi,

According to the documentation from your [website](https://bugsnag.com/docs/notifiers/laravel#laravel-older-versions) to run the bugsnag package for laravel on an older version like 4.2 you need to install ```bugsnag/bugsnag-laravel:1.*``` . That will install the current 1.6.3 version of the package. 

Till now everything is good but in the versions after 1.2.1 this class [Illuminate\Foundation\Exceptions\Handler ](https://github.com/bugsnag/bugsnag-laravel/blob/v1.6.3/src/Bugsnag/BugsnagLaravel/BugsnagExceptionHandler.php#L4)doesn't exists. Weirdly if you are running php < 5.6 with laravel 4.x the package is working but the moment you upgrade to php version 5.6.x there is an error that pops up. 
```
[ErrorException]                                                  
The use statement with non-compound name 'Bugsnag' has no effect 
```

**Comment by GrahamCampbell** [comment]
Our installation docs for Laravel 4 are available here: https://github.com/bugsnag/bugsnag-laravel#laravel-older-versions.
