### ISSUE TITLE
Call to undefined method Bugsnag_Client::setStripPath()

### ISSUE THREAD

**Issue by robdudley** [bugsnag/bugsnag-laravel#95]
I'm getting the below Error from Bugsnag in a Laravel 5.1 install.

It doesn't seem to happen on all errors but it's definitely an issue as it prevent exceptions from being sent to BugSnag and intercepts the original exception preventing debugging via the log.

```
E_ERROR: Call to undefined method Bugsnag_Client::setStripPath()
in Bugsnag\BugsnagLaravel\BugsnagLaravelServiceProvider::Bugsnag\BugsnagLaravel\{closure} called at /var/www/appRoot/vendor/bugsnag/bugsnag-laravel/src/Bugsnag/BugsnagLaravel/BugsnagLaravelServiceProvider.php (62)
```

**Comment by GrahamCampbell** [comment]
It looks like you installed an old version of the Bugsnag PHP Client library. Please let us know if you're still experiencing issues after upgrading.
