### ISSUE TITLE
[Help] Pass appVersion parameter

### ISSUE THREAD

**Issue by dimsav** [bugsnag/bugsnag-laravel#96]
Hello,

I noticed today that bugsnag can display the app version used when an exception has been thrown.

How can we pass the app version as meta information to bugsnag? Is that even possible?

Many thanks!

**Comment by kattrali** [comment]
Sure, you can set `appVersion` manually on the `$bugsnag` object. [Here is the documentation in bugsnag-php](https://github.com/bugsnag/bugsnag-php#setappversion).
