### ISSUE TITLE
Setting user metadata results in ID being reset to IP address

### ISSUE THREAD

**Issue by ArondeParon** [bugsnag/bugsnag-laravel#99]
The following code results in the `id` property from being reset to the IP address of the user.

	$error->setMetaData([
	    'user' => [
	        'id' => $user->id,
	        'name' => $user->username,
	        'email' => $user->email
	    ]
	]);

I have also tried setting only the `name` and `email` properties, but this, also, results in `id` being reset.

**Comment by GrahamCampbell** [comment]
Where are you calling this please?

**Comment by GrahamCampbell** [comment]
You can't set the user by calling setMetaData. Instead call the setUser function. Please let me know if you still have any issues.
